export default {
  'İstanbul': [
    '2. Mehmet Mesleki ve Teknik Anadolu Lisesi',
    '30 Ağustos Mesleki ve Teknik Anadolu Lisesi',
    '50. Yıl Tahran Anadolu Lisesi',
    '75. Yıl Cumhuriyet Mesleki ve Teknik Anadolu Lisesi',
    '75. Yıl Cumhuriyet Mesleki ve Teknik Anadolu Lisesi',
    '75. Yıl Devlet Malzeme Ofisi Mesleki ve Teknik Anadolu Lisesi',
    '80.yıl Nuh Çimento Anadolu Lisesi',
    'Abdurrahman Ve Nermin Bilimli Mesleki ve Teknik Anadolu Lisesi',
    'Abidin Nesimi Fatinoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Adalar Anadolu İmam Hatip Lisesi',
    'Adile Mermerci Anadolu Lisesi',
    'Adnan Menderes Anadolu Lisesi',
    'Ağva Anadolu Lisesi',
    'Ahi Evran Mesleki ve Teknik Anadolu Lisesi',
    'Ahmet Buhan Kız Anadolu İmam Hatip Lisesi',
    'Ahmet Rasim Anadolu Lisesi',
    'Ahmet Sani Gezici Mesleki ve Teknik Anadolu Lisesi',
    'Ahmet Şişman Kız Anadolu İmam Hatip Lisesi',
    'Ahmet Ünal Kız Anadolu İmam Hatip Lisesi',
    'Ahmet Yesevi Kız Anadolu İmam Hatip Lisesi',
    'Akbaba Mesleki ve Teknik Anadolu Lisesi',
    'Akif İnan Anadolu İmam Hatip Lisesi',
    'Akşemsettin Anadolu İmam Hatip Lisesi',
    'Alaattin-Nilüfer Kadayıfcioğlu Mesleki ve Teknik Anadolu Lisesi',
    'Alemdağ Anadolu İmam Hatip Lisesi',
    'Ali Akkanat Anadolu Lisesi',
    'Ali Fuat Cebesoy Kız Anadolu İmam Hatip Lisesi',
    'Ali Rıza Özderici Anadolu Lisesi',
    'Alibeyköy Anadolu Lisesi',
    'Alibeyköy Mesleki ve Teknik Anadolu Lisesi',
    'Alman Liseliler Kültür Eğitim Vakfı Özel Anadolu Lisesi',
    'Alman Liseliler Kültür Ve Eğitim Vakfı Özel İlkokulu',
    'Alman Liseliler Kültür Ve Eğitim Vakfı Özel Ortaokulu',
    'Alman Liseliler Kültür Ve Ğitim Vakfı Özel Anaokulu',
    'Alparslan Anadolu Lisesi',
    'Alparslan Mesleki ve Teknik Anadolu Lisesi',
    'Amiral Vehbi Ziya Dümer Anadolu Lisesi',
    'Arnavutköy Anadolu Lisesi',
    'Arnavutköy Haraççı İmkb Anadolu İmam Hatip Lisesi',
    'Arnavutköy Korkmaz Yiğit Anadolu Lisesi',
    'Arnavutköy Mesleki ve Teknik Anadolu Lisesi',
    'Asiye Ağaoğlu Anadolu Lisesi',
    'Asım Kibar Mesleki ve Teknik Anadolu Lisesi',
    'Asım Ülker Anadolu İmam Hatip Lisesi',
    'Atakent Anadolu Lisesi',
    'Atakent İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Ataköy Anadolu Lisesi',
    'Ataköy Cumhuriyet Anadolu Lisesi',
    'Ataşehir Anadolu Lisesi',
    'Ataşehir D. Sabancı Mesleki ve Teknik Anadolu Lisesi',
    'Ataşehir İbrahim Müteferrika Mesleki ve Teknik Anadolu Lisesi',
    'Ataşehir Kız Anadolu İmam Hatip Lisesi',
    'Ataşehir Mesleki ve Teknik Anadolu Lisesi',
    'Ataşehir R. Bayraktar Mesleki ve Teknik Anadolu Lisesi',
    'Atatürk Anadolu Lisesi',
    'Atilla Uras Anadolu Lisesi',
    'Atışalanı Anadolu Lisesi',
    'Avcılar Anadolu İmam Hatip Lisesi',
    'Avcılar Anadolu Lisesi',
    'Avcılar Mesleki ve Teknik Anadolu Lisesi',
    'Avcılar Saide Zorlu Mesleki ve Teknik Anadolu Lisesi',
    'Ayazağa Anadolu İmam Hatip Lisesi',
    'Ayazağa Anadolu Lisesi',
    'Ayşe Ege Mesleki ve Teknik Anadolu Lisesi',
    'Ayşe Erkan Anadolu Kız İmam Hatip Lisesi',
    'Bağcılar Ahi Evren Kız Anadolu İmam Hatip Lisesi',
    'Bağcılar Akşemsettin Anadolu Lisesi',
    'Bağcılar Anadolu İmam Hatip Lisesi',
    'Bağcılar Anadolu Lisesi',
    'Bağcılar Aydın Doğan Mesleki ve Teknik Anadolu Lisesi',
    'Bağcılar Edip İplik Mesleki ve Teknik Anadolu Lisesi',
    'Bağcılar Fatih Mesleki ve Teknik Anadolu Lisesi',
    'Bağcılar İbni Sina Anadolu Lisesi',
    'Bağcılar Mesleki ve Teknik Anadolu Lisesi',
    'Bağlarbaşı Mesleki ve Teknik Anadolu Lisesi',
    'Bahçelievler Anadolu Lisesi',
    'Bahçelievler Anadolu Lisesi',
    'Bahçelievler Aydın Doğan Mesleki ve Teknik Anadolu Lisesi',
    'Bahçelievler Çobançeşme Anadolu İmam Hatip Lisesi',
    'Bahçelievler Cumhuriyet Anadolu Lisesi',
    'Bahçelievler Kız Anadolu İmam Hatip Lisesi',
    'Bahçelievler Mesleki ve Teknik Anadolu Lisesi',
    'Bahçelievler Özel Aksu Fen Mektepleri Mesleki Ve Teknik Anadolu Lisesi',
    'Bahçelievler Şehit Osman Yıldiz Mesleki ve Teknik Anadolu Lisesi',
    'Bahçelievler Türk Telekom Mesleki ve Teknik Anadolu Lisesi',
    'Bahçelievler Türkiye Gazetesi Mesleki ve Teknik Anadolu Lisesi',
    'Bahçeşehir Atatürk Anadolu Lisesi',
    'Bahçeşehir İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Bakırköy 70. Yıl Mesleki ve Teknik Anadolu Lisesi',
    'Bakırköy Anadolu İmam Hatip Lisesi',
    'Bakırköy Anadolu Lisesi',
    'Bakırköy Mesleki ve Teknik Anadolu Lisesi',
    'Bakırköy Nüket Ercan Mesleki ve Teknik Anadolu Lisesi',
    'Barbaros Anadolu Lisesi',
    'Başakşehir Anadolu İmam Hatip Lisesi',
    'Başakşehir Anadolu Lisesi',
    'Başakşehir Mesleki ve Teknik Anadolu Lisesi',
    'Bayrampaşa Aliya İzzetbegoviç Kız Anadolu İmam Hatip Lisesi',
    'Bayrampaşa Mesleki ve Teknik Anadolu Lisesi',
    'Bayrampaşa Saraybosna Mesleki ve Teknik Anadolu Lisesi',
    'Bayrampaşa Tuna Mesleki ve Teknik Anadolu Lisesi',
    'Behçet Canbaz Anadolu Lisesi',
    'Behçet Kemal Çağlar Anadolu Lisesi',
    'Behiye Dr.Nevhiz Işıl Anadolu Lisesi',
    'Beşiktaş Anadolu Lisesi',
    'Beşir Balcıoğlu Anadolu Lisesi',
    'Beykoz Anadolu Lisesi',
    'Beykoz Anadoluhisarı Mesleki ve Teknik Anadolu Lisesi',
    'Beykoz Barbaros Hayrettin Paşa Mesleki ve Teknik Anadolu Lisesi',
    'Beykoz Boğaziçi Anadolu İmam Hatip Lisesi',
    'Beykoz Mesleki ve Teknik Anadolu Lisesi',
    'Beylikdüzü Azem Yükseloğlu Anadolu İmam Hatip Lisesi',
    'Beylikdüzü Cahit Zarifoğlu Anadolu Lisesi',
    'Beyoğlu Anadolu İmam Hatip Lisesi',
    'Beyoğlu Anadolu Lisesi',
    'Beyoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Beyoğlu Özel Merkez Rum İlköğretim Okulu Ve Lisesi',
    'Bingül Erdem Anadolu Lisesi',
    'Boğaziçi Mesleki ve Teknik Anadolu Lisesi',
    'Bolluca Mesleki ve Teknik Anadolu Lisesi',
    'Borsa İstanbul Başakşehir Mesleki ve Teknik Anadolu Lisesi',
    'Borsa İstanbul Zeytinburnu Anadolu Lisesi',
    'Borusan Asım Kocabıyik Mesleki ve Teknik Anadolu Lisesi',
    'Burak Bora Anadolu Lisesi',
    'Burak Bora Anadolu Lisesi',
    'Burhan Felek Anadolu Lisesi',
    'Burhaniye Anadolu İmam Hatip Lisesi',
    'Büyükçekmece Anadolu Lisesi',
    'Büyükçekmece Atatürk Anadolu Lisesi',
    'Büyükçekmece Güzelce Mesleki ve Teknik Anadolu Lisesi',
    'Büyükçekmece Mesleki ve Teknik Anadolu Lisesi',
    'Büyükçekmece Özel Cihangir Anadolu Lisesi',
    'Büyükçekmece Özel Çınar Anadolu Lisesi',
    'Büyükçekmece Özel Çınar Fen Lisesi',
    'Büyükçekmece Recep Güngör Anadolu Lisesi',
    'Büyükşehir Hüseyin Yıldız Anadolu Lisesi',
    'Cağaloğlu Anadolu Lisesi',
    'Cağaloğlu Mesleki ve Teknik Anadolu Lisesi',
    'Çağrıbey Anadolu Lisesi',
    'Cahit Zarifoğlu Anadolu İmam Hatip Lisesi',
    'Çakmaklı Cumhuriyet Anadolu Lisesi',
    'Çamlıca Kız Anadolu İmam Hatip Lisesi',
    'Çamlıca Kız Anadolu Lisesi',
    'Çapa Fen Lisesi',
    'Çatalca Anadolu İmam Hatip Lisesi',
    'Çatalca Anadolu Lisesi',
    'Çatalca Anadolu Lisesi',
    'Çatalca Arif Nihat Asya Mesleki ve Teknik Anadolu Lisesi',
    'Çatalca İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Çavuşbaşı Anadolu İmam Hatip Lisesi',
    'Çekmeköy Anadolu İmam Hatip Lisesi',
    'Celal Aras Anadolu Lisesi',
    'Çemberlitaş Anadolu Lisesi',
    'Cemil Meriç Mesleki ve Teknik Anadolu Lisesi',
    'Çengelköy Mesleki ve Teknik Anadolu Lisesi',
    'Cengizhan Anadolu Lisesi',
    'Cevat Koçak Mesleki ve Teknik Anadolu Lisesi',
    'Çevre Koleji',
    'Cibali Erkek Anadolu İmam Hatip Lisesi',
    'Cumhuriyet Anadolu Lisesi',
    'Davutpaşa Anadolu Lisesi',
    'Dede Korkut Anadolu Lisesi',
    'Dilnihat Özyeğin Anadolu Lisesi',
    'Doç. Dr. Burhan Bahriyeli Mesleki ve Teknik Anadolu Lisesi',
    'Dr. Kemal Naci Ekşi Anadolu Lisesi',
    'Dr.nurettin Erk-perihan Erk Mesleki ve Teknik Anadolu Lisesi',
    'Dr.oktay Duran Mesleki ve Teknik Anadolu Lisesi',
    'Dr.Vasıf Topçu Fen Lisesi',
    'Dündar Uçar Mesleki ve Teknik Anadolu Lisesi',
    'Durusu Hüseyin Ökten Anadolu Lisesi',
    'E.C.A Elginkan Anadolu Lisesi',
    'Eczacı Neşem Özlen Güray Anadolu Lisesi',
    'Ekrem Cevahir Anadolu İmam Hatip Lisesi',
    'Emin Yükseloğlu Kız Anadolu İmam Hatip Lisesi',
    'Emlak Konut Mimar Sinan Anadolu Lisesi',
    'Erenköy Kız Anadolu Lisesi',
    'Ergün Öner - Mehmet Öner Anadolu Lisesi',
    'Erkut Soyak Anadolu Lisesi',
    'Ertuğrul Gazi Anadolu Lisesi',
    'Esatpaşa Anadolu İmam Hatip Lisesi',
    'Esatpaşa Kız Anadolu İmam Hatip Lisesi',
    'Esenler Güzide Özdilek Anadolu İmam Hatip Lisesi',
    'Esenler Mesleki ve Teknik Anadolu Lisesi',
    'Esenler Tuna Mesleki ve Teknik Anadolu Lisesi',
    'Esenyurt Anadolu Lisesi',
    'Esenyurt Kıraç Anadolu Lisesi',
    'Esenyurt Kız Anadolu İmam Hatip Lisesi',
    'Esenyurt Nakipoğlu Cumhuriyet Anadolu Lisesi',
    'Esenyurt Toki Ali Duran Mesleki ve Teknik Anadolu Lisesi',
    'Eşref Bitlis Mesleki ve Teknik Anadolu Lisesi',
    'Etiler Anadolu Lisesi',
    'Etiler Mesleki ve Teknik Anadolu Lisesi',
    'Etiler Mesleki ve Teknik Anadolu Lisesi',
    'Etiler Mesleki ve Teknik Anadolu Lisesi',
    'Evliya Çelebi Mesleki ve Teknik Anadolu Lisesi',
    'Eyüp Anadolu Lisesi',
    'Eyüp İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Eyüp Kız Anadolu İmam Hatip Lisesi',
    'Fahreddin Kerim Gökay Anadolu Lisesi',
    'Faruk Nafiz Çamlıbel Anadolu İmam Hatip Lisesi',
    'Fatih Gelenbevi Anadolu Lisesi',
    'Fatih Kız Anadolu İmam Hatip Lisesi',
    'Fatih Mesleki ve Teknik Anadolu Lisesi',
    'Fatih Sultan Mehmet Anadolu İmam Hatip Lisesi',
    'Fatih Sultan Mehmet Mesleki ve Teknik Anadolu Lisesi',
    'Fatin Rüştü Zorlu Anadolu Lisesi',
    'Fehmi Yılmaz Mesleki ve Teknik Anadolu Lisesi',
    'Fenerbahce Anadolu Lisesi',
    'Fevzi Çakmak Anadolu Lisesi',
    'Fikriye-Nüzhet Bilgincan Mesleki ve Teknik Anadolu Lisesi',
    'Firuzan-Kemal Demironaran Mesleki ve Teknik Anadolu Lisesi',
    'Firüzköy Mesleki ve Teknik Anadolu Lisesi',
    'Fındikli Mesleki ve Teknik Anadolu Lisesi',
    'Florya Tevfik Ercan Anadolu Lisesi',
    'Fmv Özel Ayazağa Işık Lisesi',
    'Fmv Özel Işık Lisesi',
    'Fmv Özel Ispartakule Işık Lisesi',
    'Fmv. Özel Erenköy Işık Fen Lisesi',
    'Fmv. Özel Erenköy Işık Lisesi',
    'Füsun Yönder Anadolu Lisesi',
    'Galata Kız Anadolu İmam Hatip Lisesi',
    'Galata Mesleki ve Teknik Anadolu Lisesi',
    'Galatasaray Lisesi',
    'Galip Öztürk Mesleki ve Teknik Anadolu Lisesi',
    'Gazi Anadolu Lisesi',
    'Gazi Mesleki ve Teknik Anadolu Lisesi',
    'Gazi Mesleki ve Teknik Anadolu Lisesi',
    'Gaziosmanpaşa Anadolu İmam Hatip Lisesi',
    'Gaziosmanpaşa Anadolu Lisesi',
    'Gaziosmanpaşa Anadolu Lisesi',
    'Gaziosmanpaşa Mesleki ve Teknik Anadolu Lisesi',
    'Gediktaş Anadolu İmam Hatip Lisesi',
    'General Ali Rıza Ersin Mesleki ve Teknik Anadolu Lisesi',
    'Gözcübaba Anadolu İmam Hatip Lisesi',
    'Göztepe İhsan Kurşunoğlu Anadolu Lisesi',
    'Güç Kardeşler Anadolu Lisesi',
    'Gülizar Zeki Obdan Anadolu Lisesi',
    'Gültepe Anadolu İmam Hatip Lisesi',
    'Gültepe Mesleki ve Teknik Anadolu Lisesi',
    'Gümüşpala Mesleki ve Teknik Anadolu Lisesi',
    'Gümüşyaka Anadolu Lisesi',
    'Güner Akın Anadolu İmam Hatip Lisesi',
    'Güngören Anadolu Lisesi',
    'Güngören Erdem Bayazıt Anadolu Lisesi',
    'Güngören Kız Anadolu İmam Hatip Lisesi',
    'Güngören Mesleki ve Teknik Anadolu Lisesi',
    'Güngören T. Azaphan Mesleki ve Teknik Anadolu Lisesi',
    'Gürlek-Nakipoğlu Anadolu Lisesi',
    'Gürpınar İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Gürpınar Mesleki ve Teknik Anadolu Lisesi',
    'Güzeltepe Anadolu İmam Hatip Lisesi',
    'Güzelyurt Kız Anadolu İmam Hatip Lisesi',
    'Habibler Anadolu Lisesi',
    'Habire Yahşi Anadolu Lisesi',
    'Hacı Fatma Gül Mesleki ve Teknik Anadolu Lisesi',
    'Hacı Hatice Bayraktar Anadolu Lisesi',
    'Hacı İsmail Gündoğdu Çok Programlı Anadolu Lisesi',
    'Hacı Ömer Tarman Anadolu Lisesi',
    'Hacı Rahime Ulusoy Mesleki ve Teknik Anadolu Lisesi',
    'Hacı Sabancı Anadolu Lisesi',
    'Hadımköy Örfi Çetinkaya Anadolu Lisesi',
    'Hadımköy Toki Anadolu İmam Hatip Lisesi',
    'Halide Edip Adıvar Anadolu Lisesi',
    'Halide Edip Mesleki ve Teknik Anadolu Lisesi',
    'Halil Bekmezci Anadolu Lisesi',
    'Halil Kaya Gedik Mesleki ve Teknik Anadolu Lisesi',
    'Halil Rıfat Paşa Mesleki ve Teknik Anadolu Lisesi',
    'Halit Armay Mesleki ve Teknik Anadolu Lisesi',
    'Halkalı İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Halkalı Mehmet Akif Ersoy Mesleki ve Teknik Anadolu Lisesi',
    'Halkalı Mesleki ve Teknik Anadolu Lisesi',
    'Halkalı Toplu Konut Mesleki ve Teknik Anadolu Lisesi',
    'Haluk Ündeğer Anadolu Lisesi',
    'Hamidiye Etfal Mesleki ve Teknik Anadolu Lisesi',
    'Hamidiye Kız Anadolu İmam Hatip Lisesi',
    'Handan Hayrettin Yelkikanat Mesleki ve Teknik Anadolu Lisesi',
    'Harmandere Mesleki ve Teknik Anadolu Lisesi',
    'Hasan Ferruh Özgen Anadolu Lisesi',
    'Hasan Polatkan Anadolu Lisesi',
    'Hasan Şadoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Hasan-Sabriye Gümüş Anadolu lisesi',
    'Hasbahçe Kız Anadolu İmam Hatip Lisesi',
    'Haydar Akçelik Mesleki ve Teknik Anadolu Lisesi',
    'Haydar Akın Mesleki ve Teknik Anadolu Lisesi',
    'Haydarpaşa Lisesi',
    'Haydarpaşa Mesleki ve Teknik Anadolu Lisesi',
    'Hayreddin Karaman Kız Anadolu İmam Hatip Lisesi',
    'Hayrullah Kefoğlu Anadolu Lisesi',
    'Henza Akın Çolakoğlu Anadolu İmam Hatip Lisesi',
    'Heybeliada Anadolu Lisesi',
    'Hikmet Nazif Kurşunoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Hisar Eğitim Vakfı Özel Hisar Lisesi',
    'Hüseyin Avni Sipahi Mesleki ve Teknik Anadolu Lisesi',
    'Hüseyin Avni Sözen Anadolu Lisesi',
    'Hüseyin Bürge Anadolu Lisesi',
    'Hüseyin Erkan Anadolu İmam Hatip Lisesi',
    'Hüsnü M. Özyeğin Anadolu Lisesi',
    'Hüsnü Özyeğin Vakfı Alemdağ Tunç Çapa Anadolu Lisesi',
    'İbn-i Sina Mesleki ve Teknik Anadolu Lisesi',
    'İbrahim Özaydın Mesleki ve Teknik Anadolu Lisesi',
    'İbrahim Turhan Anadolu Lisesi',
    'İbrahim Yirik Mesleki ve Teknik Anadolu Lisesi',
    'İhkib Avcılar Mesleki ve Teknik Anadolu Lisesi',
    'İhkib Kağıthane Mesleki ve Teknik Anadolu Lisesi',
    'İhkib Yenibosna Mesleki ve Teknik Anadolu Lisesi',
    'İhsan Mermerci Anadolu Lisesi',
    'İhsan Nakipoğlu Anadolu İmam Hatip Lisesi',
    'İmmib Erkan Avcı Mesleki ve Teknik Anadolu Lisesi',
    'İnönü Mesleki ve Teknik Anadolu Lisesi',
    'İntaş Kız Anadolu İmam Hatip Lisesi',
    'İsmet Aktar Mesleki ve Teknik Anadolu Lisesi',
    'İsov-Dinçkök Mesleki ve Teknik Anadolu Lisesi',
    'İstanbul Anadolu İmam Hatip Lisesi',
    'İstanbul Anadolu Lisesi',
    'İstanbul Atatürk Anadolu Lisesi',
    'İstanbul Atatürk Fen Lisesi',
    'İstanbul Erkek Liseliler Eğitim Vakfı Özel Anadolu Lisesi',
    'İstanbul Erkek Liseliler Eğt. Vakfı Özel İlkokulu',
    'İstanbul Erkek Liseliler Eğt. Vakfı Özel Ortaokulu',
    'İstanbul Erkek Lisesi',
    'İstanbul Kadıköy Lisesi',
    'İstanbul Kız Anadolu İmam Hatip Lisesi',
    'İstanbul Mesleki ve Teknik Anadolu Lisesi',
    'İstanbul Ticaret Odası Mesleki ve Teknik Anadolu Lisesi',
    'İstanbul Ticaret Odası Mesleki ve Teknik Anadolu Lisesi',
    'İstanbul Ticaret Odası Mesleki ve Teknik Anadolu Lisesi',
    'İstanbul Üniversitesi Vakfı Özel Adıgüzel Güzel Sanatlar Lisesi',
    'İstanbul Üsküdar Lisesi',
    'İstanbul Vali Hayri Kozakçıoğlu Mesleki ve Teknik Anadolu Lisesi',
    'İstek Özel Acıbadem Anadolu Lisesi',
    'İstek Özel Acıbadem Fen Lisesi',
    'İstek Özel Atanur Oğuz Anadolu Lisesi',
    'İstek Özel Atanur Oğuz Fen Lisesi',
    'İstek Özel Belde Anadolu Lisesi',
    'İstek Özel Belde Fen Lisesi',
    'İstek Özel Bilge Kağan Anadolu Lisesi',
    'İstek Özel Bilge Kağan Fen Lisesi',
    'İstek Özel Kaşgarlı Mahmut Anadolu Lisesi',
    'İstek Özel Kaşgarlı Mahmut Fen Lisesi',
    'İstek Özel Kemal Atatürk Anadolu Lisesi',
    'İstek Özel Semiha Şakir Anadolu Lisesi',
    'İstek Özel Uluğbey Anadolu Lisesi',
    'İstek Özel Uluğbey Fen Lisesi',
    'İstinye Anadolu Lisesi',
    'İtosb Mesleki ve Teknik Anadolu Lisesi',
    'İtü Geliştirme Vakfı Özel Ekrem Elginkan Lisesi',
    'K. Çekmece Z. Mustafa Dalgıç Mesleki ve Teknik Anadolu Lisesi',
    'Kabataş Erkek Lisesi',
    'Kabatas Mesleki ve Teknik Anadolu Lisesi',
    'Kadir Has Anadolu Lisesi',
    'Kadıköy Anadolu Lisesi',
    'Kadıköy Erkek Anadolu İmam Hatip Lisesi',
    'Kadıköy Göztepe Mesleki ve Teknik Anadolu Lisesi',
    'Kadıköy Kız Anadolu İmam Hatip Lisesi',
    'Kadıköy Mesleki ve Teknik Anadolu Lisesi',
    'Kadırga Mesleki ve Teknik Anadolu Lisesi',
    'Kadri Yörükoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Kadriye Moroğlu Anadolu Lisesi',
    'Kağıthane Anadolu Lisesi',
    'Kağıthane Anadolu Lisesi',
    'Kağıthane İto Mesleki ve Teknik Anadolu Lisesi',
    'Kağıthane İto Mesleki ve Teknik Anadolu Lisesi',
    'Kağıthane Kız Anadolu İmam Hatip Lisesi',
    'Kalem Vakfı Özel Çamlıca Anadolu Lisesi',
    'Kandilli Kız Anadolu Lisesi',
    'Kardelen Mesleki ve Teknik Anadolu Lisesi',
    'Kartal Anadolu İmam Hatip Lisesi',
    'Kartal Anadolu Lisesi',
    'Kartal Anadolu Lisesi',
    'Kartal Atalar Mesleki ve Teknik Anadolu Lisesi',
    'Kartal Cevizli Anadolu İmam Hatip Lisesi',
    'Kartal Disk Mesleki ve Teknik Anadolu Lisesi',
    'Kartal Fatma Aliye Mesleki ve Teknik Anadolu Lisesi',
    'Kartal İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Kartal Mehmet Akif Ersoy Anadolu İmam Hatip Lisesi',
    'Kartal Mesleki ve Teknik Anadolu Lisesi',
    'Kartal Sabiha Gökçen Mesleki ve Teknik Anadolu Lisesi',
    'Kartaltepe Mesleki ve Teknik Anadolu Lisesi',
    'Kavakpınar Anadolu İmam Hatip Lisesi',
    'Kaynarca Kız Anadolu İmam Hatip Lisesi',
    'Kaynarca Şevket Sabancı Mesleki ve Teknik Anadolu Lisesi',
    'Kazım İşmen Anadolu Lisesi',
    'Kazım Karabekir Anadolu İmam Hatip Lisesi',
    'Kemal Atatürk Anadolu Lisesi',
    'Kemal Atay Mesleki ve Teknik Anadolu Lisesi',
    'Kemal Hasoğlu Anadolu İmam Hatip Lisesi',
    'Kemal Hasoğlu Anadolu Lisesi',
    'Kıraç İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Kırımlı Fazilet Olcay Anadolu Lisesi',
    'Kırımlı İsmail Rüştü Olcay Anadolu Lisesi',
    'Kocamustafapaşa Anadolu İmam Hatip Lisesi',
    'Kocasinan Mesleki ve Teknik Anadolu Lisesi',
    'Kocasinan Şehit Samet Kırbaş Mesleki ve Teknik Anadolu Lisesi',
    'Köy Hizmetleri Anadolu Lisesi',
    'Küçükçekmece Anadolu İmam Hatip Lisesi',
    'Küçükçekmece Anadolu Lisesi',
    'Küçükçekmece Atatürk Mesleki ve Teknik Anadolu Lisesi',
    'Küçükçekmece İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Küçükçekmece Mesleki ve Teknik Anadolu Lisesi',
    'Küçükkoy Anadolu İmam Hatip Lisesi',
    'Küçükköy Mesleki ve Teknik Anadolu Lisesi',
    'Küçükyalı Mesleki ve Teknik Anadolu Lisesi',
    'Küçükyalı Rezan Has Anadolu Lisesi',
    'Kumburgaz Mesleki ve Teknik Anadolu Lisesi',
    'Kurtköy Anadolu İmam Hatip Lisesi',
    'Kurtköy Anadolu Lisesi',
    'Kurtuluş Anadolu Lisesi',
    'Levent Mesleki ve Teknik Anadolu Lisesi',
    'M. Ali Büyükhanlı Mesleki ve Teknik Anadolu Lisesi',
    'M.Emin Saraç Anadolu İmam Hatip Lisesi',
    'Maçka Akif Tuncel Mesleki ve Teknik Anadolu Lisesi',
    'Madenler Mesleki ve Teknik Anadolu Lisesi',
    'Mahmutbey Mesleki ve Teknik Anadolu Lisesi',
    'Maltepe Anadolu Lisesi',
    'Maltepe Cevizli Mesleki ve Teknik Anadolu Lisesi',
    'Maltepe Kız Anadolu İmam Hatip Lisesi',
    'Maltepe Mesleki ve Teknik Anadolu Lisesi',
    'Maltepe Orhangazi Anadolu İmam Hatip Lisesi',
    'Mareşal Fevzi Çakmak Mesleki ve Teknik Anadolu Lisesi',
    'Marmara Kız Anadolu İmam Hatip Lisesi',
    'Mecidiyeköy Anadolu Lisesi',
    'Mediha Engizer Mesleki ve Teknik Anadolu Lisesi',
    'Medine Tayfur Sökmen Anadolu İmam Hatip Lisesi',
    'Mehmet Akif Ersoy Anadolu İmam Hatip Lisesi',
    'Mehmet Akif Mesleki ve Teknik Anadolu Lisesi',
    'Mehmet Baydar Anadolu Lisesi',
    'Mehmet Beyazıd Mesleki ve Teknik Anadolu Lisesi',
    'Mehmet Emin Horoz Mesleki ve Teknik Anadolu Lisesi',
    'Mehmet Niyazi Altuğ Anadolu Lisesi',
    'Mehmet Pisak Anadolu Lisesi',
    'Mehmet Rauf Mesleki ve Teknik Anadolu Lisesi',
    'Mehmet Rıfat Evyap Mesleki ve Teknik Anadolu Lisesi',
    'Mehmet Salih Bal Mesleki ve Teknik Anadolu Lisesi',
    'Mehmet Tekinalp Anadolu Lisesi',
    'Mehmetçik Anadolu Lisesi',
    'Melek Aknil Mesleki ve Teknik Anadolu Lisesi',
    'Mev Koleji Özel Basınköy Anadolu Lisesi',
    'Mev Koleji Özel Büyükçekmece Anadolu Lisesi',
    'Mev Koleji Özel Büyükçekmece Fen Lisesi',
    'Mevlana Anadolu Lisesi',
    'Mevlana Mesleki ve Teknik Anadolu Lisesi',
    'Miktat Ağaoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Mimar Sinan Anadolu İmam Hatip Lisesi',
    'Mimar Sinan Anadolu İmam Hatip Lisesi',
    'Mimar Sinan Kız Anadolu İmam Hatip Lisesi',
    'Mimar Sinan Özel Anadolu Lisesi',
    'Mimar Sinan Özel Fen Lisesi',
    'Mithatpaşa Mesleki ve Teknik Anadolu Lisesi',
    'Muhsin Adil Binal Mesleki ve Teknik Anadolu Lisesi',
    'Münevver Kemal Özver Mesleki ve Teknik Anadolu Lisesi',
    'Mustafa Barut Mesleki ve Teknik Anadolu Lisesi',
    'Mustafa Kemal Anadolu Lisesi',
    'Mustafa Kemal Anadolu Lisesi',
    'Mustafa Saffet Anadolu Lisesi',
    'Nahit Menteşe Mesleki ve Teknik Anadolu Lisesi',
    'Namık Kemal Anadolu İmam Hatip Lisesi',
    'Necip Fazıl Kısakürek Anadolu İmam Hatip Lisesi',
    'Necip Fazıl Kısakürek Mesleki ve Teknik Anadolu Lisesi',
    'Nesrin Uçmaklıoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Nevzat Ayaz Anadolu Lisesi',
    'Nilüfer Hatun Kız Anadolu İmam Hatip Lisesi',
    'Nişantaşı Anadolu Lisesi',
    'Nişantaşı Nuri Akın Anadolu Lisesi',
    'Nişantaşı Rüştü Uzel Mesleki ve Teknik Anadolu Lisesi',
    'Notre Dame De Sion',
    'Nuh Kuşçulu Mesleki ve Teknik Anadolu Lisesi',
    'Nuri Cıngillioğlu Mesleki ve Teknik Anadolu Lisesi',
    'Nurretin Topçu Kız Anadolu İmam Hatip Lisesi',
    'Öğrenciden Armağan Anadolu Lisesi',
    'Oguz Canpolat Anadolu Lisesi',
    'Ömer Çam Anadolu İmam Hatip Lisesi',
    'Ömer Nasuhi Bilmen Anadolu İmam Hatip Lisesi',
    'Örfi Çetinkaya Mesleki ve Teknik Anadolu Lisesi',
    'Orhan Cemal Fersoy Anadolu Lisesi',
    'Orhangazi Anadolu İmam Hatip Lisesi',
    'Orhangazi Anadolu İmam Hatip Lisesi',
    'Ortaköy Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
    'Oruç Reis Anadolu İmam Hatip Lisesi',
    'Osmangazi Anadolu İmam Hatip Lisesi',
    'Osmangazi Kız Anadolu İmam Hatip Lisesi',
    'Osmangazi Mesleki ve Teknik Anadolu Lisesi',
    'Otakçılar Anadolu İmam Hatip Lisesi',
    'Otocenter Mesleki ve Teknik Anadolu Lisesi',
    'Oya-Ali Keçeci Sosyal Bilimler Lisesi',
    'Özdemir Sabancı Emirgan Anadolu Lisesi',
    'Özden Cengiz Anadolu Lisesi',
    'Özel Acarkent Doğa Anadolu Lisesi',
    'Özel Acıbadem Anadolu Lisesi',
    'Özel Acıbadem Bilim Doğa Anadolu Lisesi',
    'Özel Ahmet Şimşek Anadolu Lisesi',
    'Özel Ak Kol Anadolu Lisesi',
    'Özel Ak Rida Temel Lisesi',
    'Özel Akay Anadolu Lisesi',
    'Özel Akay Temel Lisesi',
    'Özel Akşemsettin Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Alev Lisesi',
    'Özel Alman Lisesi',
    'Özel Altınay Lisesi',
    'Özel Altınay Lisesi',
    'Özel Altıyol Kavram Temel Lisesi',
    'Özel Altunizade Sevinç Temel Lisesi',
    'Özel Anabilim Anadolu Lisesi',
    'Özel Analitik Temel Lisesi',
    'Özel Anatercih Akşam Lisesi',
    'Özel Arel Anadolu Lisesi',
    'Özel Arel Fen Lisesi',
    'Özel Arnavutköy Temel Lisesi',
    'Özel Arnavutköy Ünsal Temel Lisesi',
    'Özel Artı Akşam Lisesi',
    'Özel Artı Sonsuz Anadolu Lisesi',
    'Özel Artı Sonsuz Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Artı Temel Lisesi',
    'Özel Asal Temel Lisesi',
    'Özel Aşama Akşam Lisesi',
    'Özel Aşama Anadolu Lisesi',
    'Özel Aşama Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Asfa Ahmet Mithat Anadolu Lisesi',
    'Özel Asfa Fen Lisesi',
    'Özel Ata Anadolu Lisesi',
    'Özel Atabek Anadolu Lisesi',
    'Özel Atacan Anadolu Lisesi',
    'Özel Atakent Mektebim Anadolu Lisesi',
    'Özel Atakent Nazmi Arıkan Fen Bilimleri Anadolu Lisesi',
    'Özel Atakent Nazmi Arıkan Fen Bilimleri Fen Lisesi',
    'Özel Atakent Sınav Anadolu Lisesi',
    'Özel Atalar Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Ataşehir Akşam Lisesi',
    'Özel Ataşehir Doğa Anadolu Lisesi',
    'Özel Ataşehir Farabi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Ataşehir Fen Bilimleri Temel Lisesi',
    'Özel Ataşehir Nehir Akşam Lisesi',
    'Özel Ataşehir Okyanus Anadolu Lisesi',
    'Özel Ataşehir Okyanus Fen Lisesi',
    'Özel Ataşehir Onadım Eğitim Bilimleri Temel Lisesi',
    'Özel Ataşehir Sınav Temel Lisesi',
    'Özel Ataşehir Temel Lisesi',
    'Özel Atlas Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Avcılar Bilim Doğa Anadolu Lisesi',
    'Özel Avcılar Çizgi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Avcılar Final Temel Lisesi',
    'Özel Avcılar Kültür Temel Lisesi',
    'Özel Avcılar Mektebim Anadolu Lisesi',
    'Özel Avcılar Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Avcılar Oğuz Fen Bilimleri Temel Lisesi',
    'Özel Avcılar Sınav Temel Lisesi',
    'Özel Avrasya Anadolu Lisesi',
    'Özel Avrupa Boğaziçi Akşam Lisesi',
    'Özel Avrupa Boğaziçi Anadolu Lisesi',
    'Özel Avrupa Boğaziçi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Ayça Akşam Lisesi (özel Eğitim Okulu Bünyesinde)',
    'Özel Aydos Cebir Anadolu Lisesi',
    'Özel Aytaşı Akşam Lisesi',
    'Özel Bağcı Final Temel Lisesi',
    'Özel Bağcılar Başer Akşam Lisesi',
    'Özel Bağcılar Gökşen Akşam Lisesi',
    'Özel Bağcılar Kalecik Temel Lisesi',
    'Özel Bağcılar Kültür Temel Lisesi',
    'Özel Bağcılar Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Bahariye Temel Lisesi',
    'Özel Bahçeköy Açı Lisesi',
    'Özel Bahçelievler Doğa Anadolu Lisesi',
    'Özel Bahçelievler Kültür Temel Lisesi',
    'Özel Bahçelievler Mektebim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Bahçeşehir Bilfen Anadolu Lisesi',
    'Özel Bahçeşehir Bilfen Fen Lisesi',
    'Özel Bahçeşehir Birey Temel Lisesi',
    'Özel Bahçeşehir Doğa Anadolu Lisesi',
    'Özel Bahçeşehir Fen Ve Teknoloji Lisesi',
    'Özel Bahçeşehir Final Temel Lisesi',
    'Özel Bahçeşehir Lisesi',
    'Özel Bahçeşehir Mektebim Anadolu Lisesi',
    'Özel Bahçeşehir Mektebim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Bahçeşehir Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Bahçeşehir Uğur Temel Lisesi',
    'Özel Bakırköy Akşam Lisesi',
    'Özel Bakırköy Birey Temel Lisesi',
    'Özel Bakırköy Dil Ve Konuşma Temel Lisesi',
    'Özel Bakırköy Final Temel Lisesi',
    'Özel Bakırköy Oğuzkaan Anadolu Lisesi',
    'Özel Bakırköy Sevinç Ortaokulu',
    'Özel Bakırköy Sevinç Temel Lisesi',
    'Özel Bakırköy Sınav Temel Lisesi',
    'Özel Bakırköy Valide Sultan Anadolu Kız Lisesi',
    'Özel Bakıröy Kültür Temel Lisesi',
    'Özel Balkanlar Akşam Lisesi',
    'Özel Balkanlar Koleji Anadolu Lisesi',
    'Özel Balkaya Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Başakşehir Birikim Temel Lisesi',
    'Özel Başakşehir Doğa Anadolu Lisesi',
    'Özel Başakşehir Final Temel Lisesi',
    'Özel Başakşehir Nev Anadolu Lisesi',
    'Özel Başakşehir Oğuzkaan Anadolu Lisesi',
    'Özel Başakşehir Sınav Temel Lisesi',
    'Özel Başakşehir Uğur Temel Lisesi',
    'Özel Başaran Birey Temel Lisesi',
    'Özel Başarılı Akşam Lisesi',
    'Özel Başarılı Anadolu Lisesi',
    'Özel Başer Akşam Lisesi',
    'Özel Başer Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Batı-Kent Anadolu Lisesi',
    'Özel Batıataşehir Doğa Bilim Anadolu Lisesi',
    'Özel Batışehir Doğa Anadolu Lisesi',
    'Özel Bayrampaşa Akşam Lisesi',
    'Özel Bayrampaşa Boğaziçi Temel Lisesi',
    'Özel Bayrampaşa Oğuz Fen Bilimleri Temel Lisesi',
    'Özel Bayrampaşa On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Bayrampaşa Uğur Temel Lisesi',
    'Özel Beşiktaş Boğaziçi Temel Lisesi',
    'Özel Beşiktaş Final Temel Lisesi',
    'Özel Beşiktaş Kültür Temel Lisesi',
    'Özel Beşiktaş Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Beşiktaş Sınav Temel Lisesi',
    'Özel Beşiktaş Uğur Temel Lisesi',
    'Özel Beyaz Yelken Anadolu Lisesi',
    'Özel Beykent Anadolu Lisesi',
    'Özel Beykent Doğa Anadolu Lisesi',
    'Özel Beykent Fen Lisesi',
    'Özel Beykent Okyanus Anadolu Lisesi',
    'Özel Beykent Sosyal Bilimler Lisesi',
    'Özel Beykoz Temel Lisesi',
    'Özel Beylikdüzü Ak Anadolu Lisesi',
    'Özel Beylikdüzü Anadolu Lisesi',
    'Özel Beylikdüzü Beykent Uğur Anadolu Lisesi',
    'Özel Beylikdüzü Fen Bilimleri Temel Lisesi',
    'Özel Beylikdüzü Final Anadolu Lisesi',
    'Özel Beylikdüzü Final Fen Lisesi',
    'Özel Beylikdüzü Final Temel Lisesi',
    'Özel Beylikdüzü Gökkuşağı Anadolu Lisesi',
    'Özel Beylikdüzü Kültür Temel Lisesi',
    'Özel Beylikdüzü Mektebim Anadolu Lisesi',
    'Özel Beylikdüzü Oğuzkaan Anadolu Lisesi',
    'Özel Beylikdüzü Okyanus Anadolu Lisesi',
    'Özel Beylikdüzü Sınav Temel Lisesi',
    'Özel Beylikdüzü Uğur Temel Lisesi',
    'Özel Beyoğlu Doğa Anadolu Lisesi',
    'Özel Bil Anadolu Lisesi',
    'Özel Bil Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Bilfen Anadolu Lisesi',
    'Özel Bilfen Üsküdar Fen Lisesi',
    'Özel Bilge Anadolu Lisesi',
    'Özel Bilgi Çağı Anadolu Lisesi',
    'Özel Bilgin Temel Lisesi',
    'Özel Bilim Kültür Akşam Lisesi',
    'Özel Bilim Kültür Anadolu Lisesi',
    'Özel Bilimsel Analiz Temel Lisesi',
    'Özel Bilimsel Çizgi Anadolu Lisesi',
    'Özel Bilimsel Çizgi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Biltek Anadolu Lisesi',
    'Özel Birebir Atak Temel Lisesi',
    'Özel Birebir Kişi Odaklı Çözüm Temel Lisesi',
    'Özel Birikim Hayat Anadolu Lisesi',
    'Özel Birikim Hayat Anaokulu',
    'Özel Birikim Hayat Fen Lisesi',
    'Özel Boğaziçi Eğitim İlgi Anadolu Lisesi',
    'Özel Bostancı Doğa Anadolu Lisesi',
    'Özel Buğra Anadolu Lisesi',
    'Özel Buğra Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Buğra Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Büyük Hedef Temel Lisesi',
    'Özel Büyükçekmece Akademi Anadolu Lisesi',
    'Özel Büyükçekmece Akademi Fen Lisesi',
    'Özel Büyükçekmece Doğa Anadolu Lisesi',
    'Özel Büyükçekmece Gurur Akşam Lisesi',
    'Özel Büyükçekmece Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Büyükçekmeçe Uğur Anadolu Lisesi',
    'Özel Cadde Birey Temel Lisesi',
    'Özel Çağdaş Evrensel Lider Eğitim Temel Lisesi',
    'Özel Çağdaş Fen Bilimleri Temel Lisesi',
    'Özel Çağın Anadolu Lisesi',
    'Özel Çağın Öncüsü Anadolu Lisesi',
    'Özel Çağın Öncüsü Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Çağla Anadolu Lisesi',
    'Özel Çalışlar Birey Anadolu Lisesi',
    'Özel Çamlıca Doğa Anadolu Lisesi',
    'Özel Çapa Kültür Temel Lisesi',
    'Özel Çapa Sınav Temel Lisesi',
    'Özel Çatalca Final Temel Lisesi',
    'Özel Çatalca Sınav Temel Lisesi',
    'Özel Çekmeköy Çınar Anadolu Lisesi',
    'Özel Çekmeköy Çınar Fen Lisesi',
    'Özel Çekmeköy Doğa Anadolu Lisesi',
    'Özel Çekmeköy Final Anadolu Lisesi',
    'Özel Çekmeköy Final Fen Lisesi',
    'Özel Çekmeköy Modafen Anadolu Lisesi',
    'Özel Çekmeköy Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Çekmeköy Okyanus Anadolu Lisesi',
    'Özel Çekmeköy On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Çekmeköy Prestij Temel Lisesi',
    'Özel Çekmeköy Sınav Temel Lisesi',
    'Özel Cemal Reşit Rey Anadolu Güzel Sanatlar Lisesi',
    'Özel Çengelköy Anadolu Lisesi',
    'Özel Cent Lisesi',
    'Özel Cevizlibağ Doğa Anadolu Lisesi',
    'Özel Ceyda Fen Bilimleri Temel Lisesi',
    'Özel Cihangir Anadolu Lisesi',
    'Özel Cihangir Anadolu Lisesi',
    'Özel Çınar Anadolu Lisesi',
    'Özel Çınar Fen Lisesi',
    'Özel Danişmendler Avcılar Temel Lisesi',
    'Özel Daruşşafaka Lisesi',
    'Özel Dede Korkut Anadolu Lisesi',
    'Özel Dede Korkut Anadolu Sağlık Meslek Lisesi',
    'Özel Değişim Çağı Temel Lisesi',
    'Özel Deney Fen Bilimleri Temel Lisesi',
    'Özel Denizatı Anadolu Lisesi',
    'Özel Derya Öncü Anadolu Lisesi',
    'Özel Deva Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Devler Anadolu Lisesi',
    'Özel Devran Fen Lisesi',
    'Özel Doğan Anadolu Lisesi',
    'Özel Doğu Ataşehir Doğa Anadolu Lisesi',
    'Özel Doğu Ataşehir Sevinç Anadolu Lisesi',
    'Özel Dora Maltepe Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Dörtler Temel Lisesi',
    'Özel Dudullu Uğurlu Fen Bilimleri Uğurlu Eğitim Temel Lisesi',
    'Özel Durak Anadolu Lisesi',
    'Özel Durak Mesleki Ve Teknik Anadolu Lises',
    'Özel Eda İstanbul Anadolu Lisesi',
    'Özel Ege Bilim Anadolu Lisesi',
    'Özel Ege Bilim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Eğitim Ve Yaşam Merkezi Okyanus Lisesi',
    'Özel Eğitimde Dinamik Uygulamalar Akşam Lisesi',
    'Özel Eğitimde Rasyonel Açılım Beykent Anadolu Lisesi',
    'Özel Eğitmen Anadolu Lisesi',
    'Özel Elçi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Elçi Pendik Akşam Lisesi',
    'Özel Elçibey Anadolu Sağlık Meslek Lisesi',
    'Özel Elit Gençler Akşam Lisesi',
    'Özel Enerji Anadolu Lisesi',
    'Özel Enka Lisesi',
    'Özel Erdem Anadolu Sağlık Meslek Lisesi',
    'Özel Erdil Anadolu Lisesi',
    'Özel Eresin Anadolu Lisesi',
    'Özel Eresin Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Eresin Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Erturhan Temel Lisesi',
    'Özel Eryetiş Reis Denizcilik Meslek Lisesi',
    'Özel Esayan Ermeni Lisesi',
    'Özel Esenkent Okyanus Anadolu Lisesi',
    'Özel Esenkent Okyanus Fen Lisesi',
    'Özel Esenkent Okyanus Güzel Sanatlar Lisesi',
    'Özel Esenkent Okyanus Spor Lisesi',
    'Özel Esenler Eksen Temel Lisesi',
    'Özel Esenler Kültür Temel Lisesi',
    'Özel Esenler Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Esenler Sınav Temel Lisesi',
    'Özel Esenler Uğur Temel Lisesi',
    'Özel Esenyurt Boğaziçi Temel Lisesi',
    'Özel Esenyurt Eğitimde Rasyonel Açılım Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Esenyurt Kavram Temel Lisesi',
    'Özel Esenyurt Kültür Temel Lisesi',
    'Özel Esenyurt Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Esenyurt Sınav Temel Lisesi',
    'Özel Esenyurt Uğur Temel Lisesi',
    'Özel Eşref Aydın Akşam Lisesi',
    'Özel Eşref Aydın Lisesi',
    'Özel Everest Temel Lisesi',
    'Özel Eyüboğlu Fen Lisesi',
    'Özel Eyüp Doğa Anadolu Lisesi',
    'Özel Farabi Anadolu Lisesi',
    'Özel Farabi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Fatih Çapa Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Fatih Final Temel Lisesi',
    'Özel Fatih Kültür Temel Lisesi',
    'Özel Fatih Okyanus Anadolu Lisesi',
    'Özel Fatih On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Fen Bilimleri Anadolu Lisesi',
    'Özel Fen Eğitim Bilimleri Temel Lisesi',
    'Özel Fener Rum Lisesi',
    'Özel Fenerbahçe Spor Kulübü Anadolu Lisesi',
    'Özel Feyza Çiçek 2 Anaokulu',
    'Özel Fidan Anadolu Lisesi',
    'Özel Fındıkzade Bil Temel Lisesi',
    'Özel Florya Anadolu Lisesi',
    'Özel Florya Birey Temel Lisesi',
    'Özel Florya Doğa Anadolu Lisesi',
    'Özel Florya Final Anadolu Lisesi',
    'Özel Galileo Galilei İtalyan Lisesi',
    'Özel Gaziosmanpaşa Anadolu Lisesi',
    'Özel Gaziosmanpaşa Çözüm Temel Lisesi',
    'Özel Gaziosmanpaşa Final Temel Lisesi',
    'Özel Gaziosmanpaşa Genç Kültür Temel Lisesi',
    'Özel Gaziosmanpaşa Merkez Uğur Temel Lisesi',
    'Özel Gaziosmanpaşa Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Gaziosmanpaşa On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Gaziosmanpaşa Şefkat Fen Lisesi',
    'Özel Gaziosmanpaşa Uğur Temel Lisesi',
    'Özel Gaziosmanpaşa Ünsal Temel Lisesi',
    'Özel Gaziosmanpaşa Vatan Temel Lisesi',
    'Özel Genç Akşam Lisesi',
    'Özel Genç Kültür Temel Lisesi',
    'Özel Getronagan Ermeni Anadolu Lisesi',
    'Özel Gökbora Anadolu Lisesi',
    'Özel Gökbora Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Gökjet Havacılık Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Gökjet Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Gökkuşağı Anadolu Lisesi',
    'Özel Gökkuşağı Anadolu Lisesi',
    'Özel Görkem Otelcilik Ve Turizm Meslek Lisesi',
    'Özel Gözde Ufuklar Anadolu Lisesi',
    'Özel Güller Anadolu Sağlık Meslek Lisesi',
    'Özel Güneşli Birey Temel Lisesi',
    'Özel Güneşli Doğa Anadolu Lisesi',
    'Özel Güneşli Final Anadolu Lisesi',
    'Özel Güneşli Final Fen Lisesi',
    'Özel Güneşli Okyanus Anadolu Lisesi',
    'Özel Güneşli Uğur Temel Lisesi',
    'Özel Güngören Aksu Fen Mektepleri Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Güngören Bilge Temel Lisesi',
    'Özel Güngören Mektebim Anadolu Lisesi',
    'Özel Güngören Oğuz Fen Bilimleri Temel Lisesi',
    'Özel Gurur Anadolu Meslek Lisesi',
    'Özel Gurur Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Haliç Doğa Bilim Anadolu Lisesi',
    'Özel Haliç Temel Lisesi',
    'Özel Halitağa Sınav Temel Lisesi',
    'Özel Halkalı Atakent Doğa Anadolu Lisesi',
    'Özel Halkalı Atakent Final Temel Lisesi',
    'Özel Halkalı Biltek Anadolu Lisesi',
    'Özel Halkalı Boğaziçi Temel Lisesi',
    'Özel Halkalı Çözüm Temel Lisesi',
    'Özel Halkalı Uğur Asırlık Anadolu Lisesi',
    'Özel Haseki Anadolu Sağlık Meslek Lisesi',
    'Özel Havva Ekşi Büken Anadolu Lisesi',
    'Özel Haznedar Boğaziçi Temel Lisesi',
    'Özel Hedef Çağdaş Öğretim Temel Lisesi',
    'Özel Heybelida Rum Erkek Lisesi',
    'Özel İbni Sina Anadolu Sağlık Meslek Lisesi',
    'Özel İhlas Anadolu Lisesi',
    'Özel İhlas Fen Lisesi',
    'Özel İhlas Mesleki Ve Teknik Anadolu Lisesi',
    'Özel İkitelli Osb Mesleki Ve Teknik Anadolu Lisesi',
    'Özel İkitelli Topkapı Sur Osb Mesleki Ve Teknik Anadolu Lisesi',
    'Özel İnci Ümraniye Anadolu Lisesi',
    'Özel İnci Ümraniye Mesleki Ve Teknik Anadolu Lisesi',
    'Özel İncirli Sınav Temel Lisesi',
    'Özel İncirli Uğur Temel Lisesi',
    'Özel İrfan Anadolu Lisesi',
    'Özel İrfan Fen Lisesi',
    'Özel Irmak Anadolu Lisesi',
    'Özel İstanbul Berk Anadolu Lisesi',
    'Özel İstanbul Bilim Anadolu Lisesi',
    'Özel İstanbul Bilim Fen Lisesi',
    'Özel İstanbul Birey Temel Lisesi',
    'Özel İstanbul Düzgün Akşam Lisesi',
    'Özel İstanbul Eğitim Bilimleri Temel Lisesi',
    'Özel İstanbul Eyüp Bil Temel Lisesi',
    'Özel İstanbul Fen Lisesi',
    'Özel İstanbul Hayat Anadolu Sağlık Meslek Lisesi',
    'Özel İstanbul Hazar Akşam Lisesi',
    'Özel İstanbul Hazar Anadolu Lisesi',
    'Özel İstanbul Organize Sanayi Bölgesi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel İstanbul Şafak Mesleki Ve Teknik Anadolu Lisesi',
    'Özel İtalyan Lisesi',
    'Özel Kadıköy Akşam Lisesi',
    'Özel Kadıköy Anadolu Lisesi Eğitim Vakfı İlkokulu',
    'Özel Kadıköy Arıkanlar Fen Bilimleri Temel Lisesi',
    'Özel Kadıköy Dil Ve Konuşma Temel Lisesi',
    'Özel Kadıköy Doğa Anadolu Lisesi',
    'Özel Kadıköy Doğru Cevap Temel Lisesi',
    'Özel Kadıköy Erkan Demirel Temel Lisesi',
    'Özel Kadıköy Final Temel Lisesi',
    'Özel Kadıköy Kültür Temel Lisesi',
    'Özel Kadıköy Rıhtım Final Temel Lisesi',
    'Özel Kadıköy Taç Temel Lisesi',
    'Özel Kadıköy Ugur Temel Lisesi',
    'Özel Kağıthane Çözüm Temel Lisesi',
    'Özel Kağıthane On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Kağıthane Uğur Temel Lisesi',
    'Özel Kamp Odaklı Çalışma Temel Lisesi',
    'Özel Kandilli Anadolu Lisesi',
    'Özel Kardelen Anadolu Lisesi',
    'Özel Kardelen Anadolu Sağlık Meslek Lisesi',
    'Özel Kartal Çözüm Temel Lisesi',
    'Özel Kartal Doğa Anadolu Lisesi',
    'Özel Kartal Eğitimde Rasyonel Açılım Anadolu Lisesi',
    'Özel Kartal Eğitimde Rasyonel Açılım Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Kartal Kavram Temel Lisesi',
    'Özel Kartal Kültür Temel Lisesi',
    'Özel Kartal Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Kartal Oğuz Fen Bilimleri Temel Lisesi',
    'Özel Kartal Sınav Temel Lisesi',
    'Özel Kartal Uğur Anadolu Lisesi',
    'Özel Kartal Uğur Temel Lisesi',
    'Özel Kartal Yeditepe Temel Lisesi',
    'Özel Kartal Yesevi Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Kavacık Final Temel Lisesi',
    'Özel Kavacık Uğur Temel Lisesi',
    'Özel Kayı Anadolu Lisesi',
    'Özel Kaynarca Sınav Temel Lisesi',
    'Özel Kemer Lisesi',
    'Özel Kemerburgaz Doğa Bilim Anadolu Lisesi',
    'Özel Kemerburgaz Okyanus Anadolu Lisesi',
    'Özel Kervan Kadıköy Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Kıraç Anadolu Lisesi',
    'Özel Kızılkaya Şişli Uğur Temel Lisesi',
    'Özel Kızıltoprak Temel Lisesi',
    'Özel Koşuyolu Birey Temel Lisesi',
    'Özel Küçük Prens Lisesi',
    'Özel Küçükçekmece Final Temel Lisesi',
    'Özel Küçükçekmece Halkalı Okyanus Anadolu Lisesi',
    'Özel Küçükçekmece Halkalı Okyanus Fen Lisesi',
    'Özel Küçükyalı Mevlana Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Kültür 2000 Fen Lisesi',
    'Özel Kültür Fen Lisesi',
    'Özel Kültür Lisesi',
    'Özel Kumburgaz Gurur Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Kurtköy Doğa Anadolu Lisesi',
    'Özel Kuzey Anadolu Lisesi',
    'Özel Mahmut Kızılateş Anadolu Lisesi',
    'Özel Mahmut Kızılateş Fen Lisesi',
    'Özel Mahmut Ön Anadolu Lisesi',
    'Özel Maltepe Anadolu Lisesi',
    'Özel Maltepe Birey Temel Lisesi',
    'Özel Maltepe Cevizli Uğur Anadolu Lisesi',
    'Özel Maltepe Derece Temel Lisesi',
    'Özel Maltepe Final Temel Lisesi',
    'Özel Maltepe Gökyüzü Fen Lisesi',
    'Özel Maltepe İstanbul Eğitim Bilimleri Temel Lisesi',
    'Özel Maltepe Kültür Temel Lisesi',
    'Özel Maltepe Oğuzkaan Anadolu Lisesi',
    'Özel Maltepe Uğur Anadolu Lisesi',
    'Özel Maltepe Uğur Temel Lisesi',
    'Özel Marmara Evleri İhlas Anadolu Lisesi',
    'Özel Marmara Evleri İhlas Fen Lisesi',
    'Özel Marmara Evleri On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Marmara Fen Lisesi',
    'Özel Marmara Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Marmara Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Matematik Ve Edebiyat Bilimleri Temel Lisesi',
    'Özel Mavigün Anadolu Lisesi',
    'Özel Mavigün Fen Lisesi',
    'Özel Mecidiyeköy Final Temel Lisesi',
    'Özel Mecidiyeköy Sınav Temel Lisesi',
    'Özel Medeniyet Anadolu Lisesi',
    'Özel Mef Lisesi',
    'Özel Mektebim Anadolu Lisesi',
    'Özel Mektebim Anaokulu',
    'Özel Mektebim Fen Lisesi',
    'Özel Mektebim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Mektebim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Mercan Çağrı Anadolu Lisesi',
    'Özel Mesleğim Akşam Lisesi',
    'Özel Mesleğim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Metrokent Final Temel Lisesi',
    'Özel Mimaroba Sınav Temel Lisesi',
    'Özel Mimarsinan Okyanus Anadolu Lisesi',
    'Özel Moda Mimar Sinan Anadolu Güzel Sanatlar Lisesi',
    'Özel Mürüvvet Evyap Fen Lisesi',
    'Özel Mustafa Orta Temel Lisesi',
    'Özel Nasibe Eryetiş Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Nev Anadolu Lisesi',
    'Özel Nilgün Doğay Anadolu Lisesi',
    'Özel Nilgün Doğay Lisesi',
    'Özel Nilgün Eroğlu Anadolu Lisesi',
    'Özel Nişantaşı Bire Bir Temel Lisesi',
    'Özel Nitelikli Eğitim Topluluğu Temel Lisesi',
    'Özel Nitelikli Umutlu Nesiller Anadolu Lisesi',
    'Özel Oğuzkaan Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Okan Anadolu Lisesi',
    'Özel Okyanus Fen Ve Proje Lisesi',
    'Özel Ölçek Temel Lisesi',
    'Özel Özgür Önder Akşam Lisesi',
    'Özel Pangaltı Ermeni Anadolu Lisesi',
    'Özel Pendik Biltek Anadolu Lisesi',
    'Özel Pendik Birey Temel Lisesi',
    'Özel Pendik Birikim Anadolu Lisesi',
    'Özel Pendik Birikim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Pendik Birikim Temel Lisesi',
    'Özel Pendik Doğru Cevap Temel Lisesi',
    'Özel Pendik Final Temel Lisesi',
    'Özel Pendik İkbal Anadolu Lisesi',
    'Özel Pendik Kültür Temel Lisesi',
    'Özel Pendik Oğuz Fen Bilimleri Temel Lisesi',
    'Özel Pendik Sınav Temel Lisesi',
    'Özel Pendik Uğur Temel Lisesi',
    'Özel Pera Güzel Sanatlar Lisesi',
    'Özel Pi Kare Temel Lisesi',
    'Özel Pozitif Değişim Temel Lisesi',
    'Özel Rotam Temel Lisesi',
    'Özel Rumeli Anadolu Lisesi',
    'Özel Şafak Anadolu Lisesi',
    'Özel Şafak Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Safran Temel Lisesi',
    'Özel Sahakyan Nunyan Ermeni Lisesi',
    'Özel Sancaktepe Birikim Anadolu Lisesi',
    'Özel Sancaktepe Birikim Fen Lisesi',
    'Özel Sancaktepe Final Temel Lisesi',
    'Özel Sancaktepe Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Sancaktepe Okyanus Anadolu Lisesi',
    'Özel Sancaktepe Sınav Temel Lisesi',
    'Özel Saran Eller Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Sarıyer Doğa Anadolu Lisesi',
    'Özel Şaşkın Bakkal Sevinç Temel Lisesi',
    'Özel Sayısal Bil Temel Lisesi',
    'Özel Sedat Şener Temel Lisesi',
    'Özel Sefaköy Final Temel Lisesi',
    'Özel Sefaköy Kültür Temel Lisesi',
    'Özel Sefaköy Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Sefaköy Sınav Temel Lisesi',
    'Özel Sefaköy Uğur Temel Lisesi',
    'Özel Sentez Eğitim Temel Lisesi',
    'Özel Sevinç Ataşehir Anadolu Lisesi',
    'Özel Seyrantepe Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Sezin Lisesi',
    'Özel Şile Bilgi Temel Lisesi',
    'Özel Silivri Kokpit Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Silivri Marmara Motorlu Taşıt Sürücüleri Kursu',
    'Özel Silivri Mektebim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Silivri Meva Anadolu Lisesi',
    'Özel Silivri Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Silivri Uğur Temel Lisesi',
    'Özel Sinerji Temel Lisesi',
    'Özel Şirinevler Birikim Temel Lisesi',
    'Özel Şirinevler Sınav Temel Lisesi',
    'Özel Şirinevler Uğur Temel Lisesi',
    'Özel Şişli Açı Anadolu Lisesi',
    'Özel Şişli Bilim Doğa Anadolu Lisesi',
    'Özel Şişli Boğaziçi Temel Lisesi',
    'Özel Şişli Onadım Eğitim Bilimleri Temel Lisesi',
    'Özel Siyah Martı Sınav Temel Lisesi',
    'Özel Sınav Temel Lisesi',
    'Özel Sınav Temel Lisesi',
    'Özel Soyak Final Temel Lisesi',
    'Özel Soylu Bilge Temel Lisesi',
    'Özel Sultan Fatih Anadolu Lisesi',
    'Özel Sultan Fatih Fen Lisesi',
    'Özel Sultan Sınav Temel Lisesi',
    'Özel Sultanbeyli Birikim Temel Lisesi',
    'Özel Sultanbeyli Düzgün Akşam Lisesi',
    'Özel Sultanbeyli Elçi Akşam Lisesi',
    'Özel Sultanbeyli Kültür Temel Lisesi',
    'Özel Sultanbeyli Uğur Temel Lisesi',
    'Özel Sultangazi Çözüm Temel Lisesi',
    'Özel Sultangazi Kültür Temel Lisesi',
    'Özel Sultangazi Uğur Temel Lisesi',
    'Özel Süreyyapaşa Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Surp Haç Ermeni Lisesi',
    'Özel Tam Donanım Temel Lisesi',
    'Özel Tarabya Anadolu Lisesi',
    'Özel Taşdelen Bahçeşehir Anadolu Lisesi',
    'Özel Taşdelen Bahçeşehir Fen Ve Teknoloji Lisesi',
    'Özel Taşdelen Uğur Anadolu Lisesi',
    'Özel Ted Rönesans Anadolu Lisesi',
    'Özel Tem Seyrantepe Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Tercih Akşam Lisesi',
    'Özel Tercih Anadolu Lisesi',
    'Özel Tercih Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Tümevarım Temel Lisesi',
    'Özel Turem Akşam Lisesi',
    'Özel Turem Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Tutkum Fen Bilimleri Temel Lisesi',
    'Özel Tuzla Doğa Anadolu Lisesi',
    'Özel Tuzla Doğru Cevap Temel Lisesi',
    'Özel Tuzla Eğitmen İlkokulu',
    'Özel Tuzla Eğitmen Temel Lisesi',
    'Özel Tuzla Nazmi Arıkan Fen Bilimleri Temel Lisesi',
    'Özel Üç Renk Koleji Anadolu Lisesi',
    'Özel Uğur Anadolu Lisesi',
    'Özel Uğur Anadolu Lisesi',
    'Özel Uğur Avcılar Anadolu Lisesi',
    'Özel Uğur Hazırlık Anadolu Lisesi',
    'Özel Uğur Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Ümraniye Aşama Akşam Lisesi',
    'Özel Ümraniye Aşama Anadolu Lisesi',
    'Özel Ümraniye Birikim Temel Lisesi',
    'Özel Ümraniye Boğaziçi Temel Lisesi',
    'Özel Ümraniye Çağın Akşam Lisesi',
    'Özel Ümraniye Final Temel Lisesi',
    'Özel Ümraniye Gökkuşağı Anadolu Lisesi',
    'Özel Ümraniye Gökkuşağı Fen Lisesi',
    'Özel Ümraniye Kızılkaya Uğur Temel Lisesi',
    'Özel Ümraniye Kültür Temel Lisesi',
    'Özel Ümraniye Mektebim Anadolu Lisesi',
    'Özel Ümraniye On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Ümraniye Sınav Temel Lisesi',
    'Özel Ümraniye Umut Anadolu Lisesi',
    'Özel Umut Akşam Lisesi',
    'Özel Ünsev Fen Bilimleri Anadolu Lisesi',
    'Özel Üsküdar Bağlarbaşı Anadolu Lisesi',
    'Özel Üsküdar Birey Temel Lisesi',
    'Özel Üsküdar Sınav Temel Lisesi',
    'Özel Vatan Sınav Temel Lisesi',
    'Özel Vatan Temel Lisesi',
    'Özel Vital Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Vizyon Anadolu Lisesi',
    'Özel Vizyon Anadolu Lisesi',
    'Özel Yakacık Doğa Anadolu Lisesi',
    'Özel Yavuzlar Temel Lisesi',
    'Özel Yeditepe Temel Lisesi',
    'Özel Yeni Çağrı Akşam Lisesi',
    'Özel Yeni Hayat Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Yeni Yıldız Anadolu Lisesi',
    'Özel Yeşil Turkuaz Akşam Lisesi',
    'Özel Yeşilpınar On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Yetkin Akşam Lisesi',
    'Özel Yıldız Anadolu Lisesi',
    'Özel Yıldızlar Anadolu Lisesi',
    'Özel Yönelim Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Yüz 12 Mesleki Ve Teknik Anadolu Lisesi',
    'Özel Zapyon Rum Lisesi',
    'Özel Zeytinburnu Artı Akşam Lisesi',
    'Özel Zeytinburnu On Adım Eğitim Bilimleri Temel Lisesi',
    'Özel Zeytinburnu Sınav Temel Lisesi',
    'Özel Zeytinburnu Uğur Temel Lisesi',
    'Özel Zoğrafyon Rum Lisesi Ve Ticaret Okulu',
    'Özgür Boza Okulları',
    'Pagev Mesleki ve Teknik Anadolu Lisesi',
    'Paşabahçe Ahmet Ferit İnal Anadolu Lisesi',
    'Pendik Ali Yakup Cenkçiler Anadolu İmam Hatip Lisesi',
    'Pendik Anadolu Lisesi',
    'Pendik Barbaros Hayrettin Paşa Mesleki ve Teknik Anadolu Lisesi',
    'Pendik Esenler Kız Anadolu İmam Hatip Lisesi',
    'Pendik Fatih Anadolu Lisesi',
    'Pendik İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Pendik İto Mesleki ve Teknik Anadolu Lisesi',
    'Pendik Mesleki ve Teknik Anadolu Lisesi',
    'Pendik Ömer Öztop Anadolu İmam Hatip Lisesi',
    'Pendik Türk Telekom Mesleki ve Teknik Anadolu Lisesi',
    'Pendik Yunus Emre Mesleki ve Teknik Anadolu Lisesi',
    'Pertevniyal Lisesi',
    'Piri Reis Mesleki ve Teknik Anadolu Lisesi',
    'Plevne Anadolu Lisesi',
    'Prof Dr. Fuat Sezgin Fen Lisesi',
    'Prof. Dr. Hulusi Behçet Mesleki ve Teknik Anadolu Lisesi',
    'Prof. Dr. İbrahim Canan Anadolu Lisesi',
    'Prof. Dr. Mümtaz Turhan Sosyal Bilimler Lisesi',
    'Prof. Dr. Sabahattin Zaim Anadolu Lisesi',
    'Prof.dr. Necmettin Erbakan Kız Anadolu İmam Hatip Lisesi',
    'Prof.dr.muhammet Tayyip Okiç Anadolu İmam Hatip Lisesi',
    'Profilo Mesleki ve Teknik Anadolu Lisesi',
    'Profilo Mesleki ve Teknik Anadolu Lisesi',
    'Rami Atatürk Anadolu Lisesi',
    'Rauf Denktaş Mesleki ve Teknik Anadolu Lisesi',
    'Recep Tayyip Erdoğan Kız Anadolu İmam Hatip Lisesi',
    'Refhan Tümer Mesleki ve Teknik Anadolu Lisesi',
    'Rıfat Canayakın Anadolu İmam Hatip Lisesi',
    'Robert Kolej',
    'Rosvita-Timur İmrağ Mesleki ve Teknik Anadolu Lisesi',
    'Rotary 100.Yıl Anadolu Lisesi',
    'Rüştü Akın Mesleki ve Teknik Anadolu Lisesi',
    'Sabancı 50. Yıl Anadolu Lisesi',
    'Sağmalcılar Anadolu Lisesi',
    'Saint Benoit',
    'Saint Joseph',
    'Saint Michel',
    'Sainte Pulcherie',
    'Şair Abay Konanbay Anadolu Lisesi',
    'Sakıp Sabancı Anadolu Lisesi',
    'Samandıra Kız Anadolu İmam Hatip Lisesi',
    'Samandıra Mesleki ve Teknik Anadolu Lisesi',
    'Samiha Ayverdi Anadolu Lisesi',
    'Sancaktepe Anadolu Lisesi',
    'Sancaktepe Aziz Bayraktar Anadolu İmam Hatip Lisesi',
    'Sancaktepe Eyüp Sultan Mesleki ve Teknik Anadolu Lisesi',
    'Sancaktepe Fatih Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
    'Sankt Georg Avusturya Lisesi',
    'Sarıgazi Mesleki ve Teknik Anadolu Lisesi',
    'Sarıyer Hüseyin Kalkavan Mesleki ve Teknik Anadolu Lisesi',
    'Sarıyer Kız Anadolu İmam Hatip Lisesi',
    'Sarıyer Mesleki ve Teknik Anadolu Lisesi',
    'Sefaköy Anadolu Lisesi',
    'Şehit Adil Büyükcengiz Anadolu İmam Hatip Lisesi',
    'Şehit Binbaşı Bedir Karabıyik Mesleki ve Teknik Anadolu Lisesi',
    'Şehit Büyükelçi Galip Balkar Mesleki ve Teknik Anadolu Lisesi',
    'Şehit Büyükelçi İsmail Erez Mesleki ve Teknik Anadolu Lisesi',
    'Şehit Cengiz Sarıbaş Mesleki ve Teknik Anadolu Lisesi',
    'Şehit Er Çağlar Mengü Anadolu İmam Hatip Lisesi',
    'Şehit İlhan Varank Fen Lisesi',
    'Şehit Öğretmen Hüseyin Ağırman Mesleki ve Teknik Anadolu Lisesi',
    'Şehremini Anadolu Lisesi',
    'Selahaddin Eyyubi Mesleki ve Teknik Anadolu Lisesi',
    'Selahattin Eyyubi Anadolu İmam Hatip Lisesi',
    'Selçuk Mesleki ve Teknik Anadolu Lisesi',
    'Selimiye Mesleki ve Teknik Anadolu Lisesi',
    'Selimpaşa Anadolu İmam Hatip Lisesi',
    'Selimpaşa Atatürk Anadolu Lisesi',
    'Selimpaşa İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Semiha Şakir Anadolu Lisesi',
    'Şenesenevler Mualla Selcanoğlu Mesleki ve Teknik Anadolu Lisesi',
    'Şerife Baldöktü Mesleki ve Teknik Anadolu Lisesi',
    'Sev Amerikan Koleji',
    'Şeyh Şamil Mesleki ve Teknik Anadolu Lisesi',
    'Seyrantepe Dr. Sadık Ahmet Mesleki ve Teknik Anadolu Lisesi',
    'Şile Anadolu İmam Hatip Lisesi',
    'Şile Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
    'Şile Mesleki ve Teknik Anadolu Lisesi',
    'Silivri Anadolu Lisesi',
    'Silivri Mesleki ve Teknik Anadolu Lisesi',
    'Silivri Necip Sarıbekir Mesleki ve Teknik Anadolu Lisesi',
    'Şişli Anadolu Lisesi',
    'Şişli Kervansaray Mesleki ve Teknik Anadolu Lisesi',
    'Şişli Mesleki ve Teknik Anadolu Lisesi',
    'Siyavuşpaşa Mesleki ve Teknik Anadolu Lisesi',
    'Suadiye Hacı Mustafa Tarman Anadolu Lisesi',
    'Suat Terimer Anadolu Lisesi',
    'Sudi Özkan Mesleki ve Teknik Anadolu Lisesi',
    'Şükran Ülgezen Mesleki ve Teknik Anadolu Lisesi',
    'Şule Yüksel Şenler Kız Anadolu İmam Hatip Lisesi',
    'Süleyman Demirel Anadolu Lisesi',
    'Süleyman Nazif Anadolu Lisesi',
    'Süleyman Şah Kız Anadolu İmam Hatip Lisesi',
    'Sultan Alparslan Anadolu İmam Hatip Lisesi',
    'Sultan Selim Mesleki ve Teknik Anadolu Lisesi',
    'Sultanahmet Mesleki ve Teknik Anadolu Lisesi',
    'Sultanahmet Suphi Paşa Mesleki ve Teknik Anadolu Lisesi',
    'Sultanbeyli Anadolu Lisesi',
    'Sultanbeyli İbrahim Hakkı Mesleki ve Teknik Anadolu Lisesi',
    'Sultanbeyli Kız Anadolu İmam Hatip Lisesi',
    'Sultanbeyli Mesleki ve Teknik Anadolu Lisesi',
    'Sultanbeyli Sabiha Gökçen Mesleki ve Teknik Anadolu Lisesi',
    'Sultangazi Atatürk Mesleki ve Teknik Anadolu Lisesi',
    'Sultangazi Mesleki ve Teknik Anadolu Lisesi',
    'Sultangazi Nene Hatun Mesleki ve Teknik Anadolu Lisesi',
    'T.v. Özel Şişli Terakki Fen Lisesi',
    'T.v. Özel Şişli Terakki Lisesi',
    'Tarık Buğra Anadolu Lisesi',
    'Taşdelen İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Tasev Mesleki ve Teknik Anadolu Lisesi',
    'Taşoluk Anadolu Lisesi',
    'Teb Ataşehir Anadolu Lisesi',
    'Ted İstanbul Koleji Vakfı Özel Lisesi',
    'Ted Özel Atakent Anadolu Lisesi',
    'Tenzile Erdoğan Kız Anadolu İmam Hatip Lisesi',
    'Tepecik Hüsnü M. Özyeğin Anadolu Lisesi',
    'Tepekent Anadolu Lisesi',
    'Terakki Vakfı Özel Şişli Terakki Tepeören Anadolu Lisesi',
    'Terazidere Prof.ibrahim Ve Feti Pirlepeli Mesleki ve Teknik Anadolu Lisesi',
    'Tev Ezel Gülen Kıray Mesleki ve Teknik Anadolu Lisesi',
    'TEV İnanç Türkeş Özel Lisesi',
    'Toki Atakent Mesleki ve Teknik Anadolu Lisesi',
    'Toki Celalettin Ökten Anadolu İmam Hatip Lisesi',
    'Toki Cumhuriyet Anadolu Lisesi',
    'Toki Güneşparkevleri Kız Anadolu İmam Hatip Lisesi',
    'Toki Halkalı Anadolu İmam Hatip Lisesi',
    'Toki Kayaşehir Anadolu Lisesi',
    'Toki Kayaşehir Mesleki ve Teknik Anadolu Lisesi',
    'Toki Yahya Kemal Mesleki ve Teknik Anadolu Lisesi',
    'Tolga Çınar Mesleki ve Teknik Anadolu Lisesi',
    'Tuğrul Bey Anadolu Lisesi',
    'Turgut Reis Mesleki ve Teknik Anadolu Lisesi',
    'Turhan Feyzioğlu Mesleki ve Teknik Anadolu Lisesi',
    'Türk Kızılayı Kartal Anadolu Lisesi',
    'Türk Telekom Anadolu Lisesi',
    'Türkiye Çimento Müstahsilleri Birliği Mesleki ve Teknik Anadolu Lisesi',
    'Tuzla Anadolu Lisesi',
    'Tuzla Cezeri Mesleki ve Teknik Anadolu Lisesi',
    'Tuzla Halil Türkkan Anadolu İmam Hatip Lisesi',
    'Tuzla İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Tuzla Mahir İz Anadolu İmam Hatip Lisesi',
    'Tuzla Mesleki ve Teknik Anadolu Lisesi',
    'Tuzla Orhanlı Mesleki ve Teknik Anadolu Lisesi',
    'Tuzla Süleyman Demirel Mesleki ve Teknik Anadolu Lisesi',
    'Ulus Özel Musevi Lisesi',
    'Uluslararası Fatih Sultan Mehmet Anadolu İmam Hatip Lisesi',
    'Uluslararası Pendik Kız Anadolu İmam Hatip Lisesi',
    'Ümraniye Anadolu İmam Hatip Lisesi',
    'Ümraniye Anadolu Lisesi',
    'Ümraniye Atatürk Mesleki ve Teknik Anadolu Lisesi',
    'Ümraniye Cumhuriyet Mesleki ve Teknik Anadolu Lisesi',
    'Ümraniye Merkez Anadolu Lisesi',
    'Ümraniye Mesleki ve Teknik Anadolu Lisesi',
    'Üsküdar Ahmet Keleşoğlu Anadolu Lisesi',
    'Üsküdar Ahmet Keleşoğlu Anadolu Lisesi',
    'Üsküdar Amerikan Lisesi',
    'Üsküdar Anadolu İmam Hatip Lisesi',
    'Üsküdar Cumhuriyet Mesleki ve Teknik Anadolu Lisesi',
    'Üsküdar Haydarpasa Bülent Akarcalı Mesleki ve Teknik Anadolu Lisesi',
    'Üsküdar İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Üsküdar Mesleki ve Teknik Anadolu Lisesi',
    'Üsküdar Zeynep Kamil Mesleki ve Teknik Anadolu Lisesi',
    'Vali Muammer Güler Sosyal Bilimler Lisesi',
    'Validebağ Mesleki ve Teknik Anadolu Lisesi',
    'Vatan Mesleki ve Teknik Anadolu Lisesi',
    'Vefa Lisesi',
    'Vefa Poyraz Anadolu Lisesi',
    'Vehbi Koç Vakfı Koç Özel Lisesi',
    'Vehbi Koç Vakfı Mesleki ve Teknik Anadolu Lisesi',
    'Velibaba Mesleki ve Teknik Anadolu Lisesi',
    'Yahya Kemal Beyatlı Anadolu Lisesi',
    'Yahya Kemal Beyatlı Mesleki ve Teknik Anadolu Lisesi',
    'Yakacık Mesleki ve Teknik Anadolu Lisesi',
    'Yakacık Yüksel İlhan Alanyalı Mesleki ve Teknik Anadolu Lisesi',
    'Yaşar Acar Fen Lisesi',
    'Yaşar Dedeman Anadolu İmam Hatip Lisesi',
    'Yavuz Selim Anadolu İmam Hatip Lisesi',
    'Yedikule Anadolu Lisesi',
    'Yenibosna Anadolu İmam Hatip Lisesi',
    'Yenibosna Mesleki ve Teknik Anadolu Lisesi',
    'Yenilevent Anadolu Lisesi',
    'Yeşilköy 50. Yıl Anadolu Lisesi',
    'Yeşilköy Anadolu Lisesi',
    'Yüksel-İlhan Alanyalı Fen Lisesi',
    'Yunus Emre Anadolu İmam Hatip Lisesi',
    'Yunus Emre Anadolu İmam Hatip Lisesi',
    'Yunus Emre Mesleki ve Teknik Anadolu Lisesi',
    'Zeytinburnu İdmib Mesleki ve Teknik Anadolu Lisesi',
    'Zeytinburnu İmkb Mesleki ve Teknik Anadolu Lisesi',
    'Zeytinburnu Kız Anadolu İmam Hatip Lisesi',
    'Zeytinburnu M. İhsan Mermerci Mesleki ve Teknik Anadolu Lisesi',
    'Zeytinburnu Merkezefendi Anadolu İmam Hatip Lisesi',
    'Zeytinburnu Mesleki ve Teknik Anadolu Lisesi',
    'Zeytinburnu Trisad Mesleki ve Teknik Anadolu Lisesi',
    'Zincirlikuyu İsov Mesleki ve Teknik Anadolu Lisesi',
    'Ziya Kalkavan Mesleki ve Teknik Anadolu Lisesi',
    'Zühtü Kurtulmuş Anadolu Lisesi'
  ],
  'Ankara': [
    'Ted Ankara Koleji',
    'Ankara Sınav Koleji',
    'Özel Maya Okulları Oran Yerleşkesi',
    'Özel Maya Okulları İncek Yerleşkesi',
    'Maya Okulları İncek Özel Anadolu Lisesi',
    'Nesibe Aydın Gölbaşı Özel Lisesi',
    'Nesibe Aydın Yıldızlar Özel Lisesi',
    'Nesibe Aydın Çankaya Özel Lisesi',
    'Odtü Geliştirme Vakfı Özel Lisesi',
    'Özel Bilkent Lisesi',
    'Özel Sembol Anadolu Lisesi',
    'Özel Birlik Doğa Bilim Anadolu Lisesi',
    'Özel Çukurambar Doğa Anadolu Lisesi',
    'Özel İncek Doğa Anadolu Lisesi',
    'Özel Keçiören Doğa Anadolu Lisesi',
    'Özel Çayyolu Doğa Anadolu Lisesi',
    'Özel Batıkent Doğa Anadolu Lisesi',
    'Özel Bağlıca Doğa Anadolu Lisesi',
    'Özel Eryaman Doğa Bilim Anadolu Lisesi',
    'Yenimahalle Açı Koleji',
    'Çukurambar Açı Koleji',
    'Cevizlidere Açı Koleji',
    'Özel Batıkent Final Anadolu Lisesi',
    'Özel Çayyolu Final Anadolu Lisesi',
    'Özel Elvankent Final Anadolu Lisesi',
    'Özel Elvankent Final Fen Lisesi',
    'Özel Eryaman Final Anadolu Lisesi',
    'Özel Oran Final Anadolu Lisesi',
    'Özel Parktwin Final Fen Lisesi',
    'Akyurt Çok Programlı Lisesi',
    'Akyurt Lisesi',
    'Akyurt Prof. Dr. Nusret Fişek Sağlık Meslek Lisesi',
    'Akyurt Sağlık Meslek Lisesi',
    'Altındağ Ahmet Yesevi Lisesi',
    'Altındağ Ahmet Yesevi Lisesi (Yabancı Dil Ağırlıklı)',
    'Altındağ Anadolu Ticaret Meslek Lisesi',
    'Altındağ Anafartalar Lisesi',
    'Altındağ Aydınlıkevler İnönü Lisesi (Yabancı Dil Ağırlıklı)',
    'Altındağ Aydınlıkevler İnönü Lisesi',
    'Altındağ Doğantepe Çok Programlı Lisesi',
    'Altındağ Doğantepe Lisesi',
    'Altındağ Doğantepe Lisesi (Yabancı Dil Ağırlıklı)',
    'Altındağ Esenevler Lisesi',
    'Altındağ Esenevler Lisesi (Yabancı Dil Ağırlıklı)',
    'Altındağ Hacı Bayram İmam Hatip Lisesi',
    'Altındağ İmkb Ticaret Meslek Lisesi',
    'Altındağ İskitler Anadolu Meslek Lisesi',
    'Altındağ İskitler Anadolu Teknik Lisesi',
    'Altındağ İskitler Endüstri Meslek Lisesi',
    'Altındağ İskitler Teknik Lisesi',
    'Altındağ K.yurtbilir İşitme Engelliler Meslek Lisesi ',
    'Altındağ Şerife Uludağlı Kız Meslek Lisesi',
    'Altındağ Uluğbey Lisesi',
    'Altındağ Uluğbey Lisesi (Yabancı Dil Ağırlıklı)',
    'Altındağ Yeşilöz Lisesi',
    'Altındağ Yeşilöz Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Abidinpaşa Akşam Lisesi',
    'Ankara Abidinpaşa Anadolu Meslek Lisesi',
    'Ankara Abidinpaşa Anadolu Meslek Lisesi',
    'Ankara Abidinpaşa Endüstri Meslek Lisesi',
    'Ankara Abidinpaşa Lisesi',
    'Ankara Abidinpaşa Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Abidinpaşa Prof.dr.r.üner Sağlık Meslek Lisesi',
    'Ankara Abidinpaşa Sağlık Meslek Lisesi',
    'Ankara Abidinpaşa Teknik Lisesi',
    'Ankara Acil Yard.trafik Has.sağlık Meslek Lisesi',
    'Ankara Adalet Meslek Lisesi',
    'Ankara Ağaç Ve Metal İşleri Meslek Lisesi',
    'Ankara Akdere Akşam Lisesi',
    'Ankara Akşam Ticaret Lisesi',
    'Ankara Aktaş Atatürk Endüstri Meslek Lisesi',
    'Ankara Aktaş Endüstri Meslek Lisesi',
    'Ankara Aktepe Lisesi',
    'Ankara Aktepe Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Anadolu Basın Yayın Reklam.lisesi',
    'Ankara Anadolu Basın Yayın Reklamcılık Lisesi',
    'Ankara Anadolu Güzel Sanatlar Lisesi',
    'Ankara Anadolu İletişim Meslek Lisesi',
    'Ankara Anadolu İletişim Teknik Lisesi',
    'Ankara Anadolu Lisesi',
    'Ankara Anadolu Meteoroloji Meslek Lisesi',
    'Ankara Anadolu Otel ve Turizm Meslek Lisesi',
    'Ankara Anadolu Sekreterlik Meslek Lisesi',
    'Ankara Anadolu Tapu Ve Kadastro Meslek Lisesi',
    'Ankara Anadolu Ticaret Meslek Lisesi',
    'Ankara Anafartalar Akşam Lisesi',
    'Ankara Anafartalar Anadolu Lisesi',
    'Ankara Anafartalar Anadolu ticaret Meslek Lisesi',
    'Ankara Anafartalar Ticaret Meslek Lisesi',
    'Ankara Anıttepe Lisesi',
    'Ankara Anıttepe Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Atakule Meslek Lisesi',
    'Ankara Atatürk Akşam Lisesi',
    'Ankara Atatürk Anadolu Kız Meslek Lisesi',
    'Ankara Atatürk Anadolu Lisesi',
    'Ankara Atatürk Endüstri Meslek Lisesi',
    'Ankara Atatürk Kız Meslek Lisesi',
    'Ankara Atatürk Kız Teknik Lisesi',
    'Ankara Atatürk Lisesi',
    'Ankara Atatürk Teknik Lisesi',
    'Ankara Aydınlıkevler Anadolu iletişim Meslek Lisesi',
    'Ankara Aydınlıkevler Lisesi',
    'Ankara Aydınlıkevler Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Aydınlıkevler Ticaret Meslek L.',
    'Ankara Ayrancı Akşam Ticaret Meslek Lisesi',
    'Ankara Ayrancı Lisesi',
    'Ankara Ayrancı Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Ayrancı Ticaret Meslek Lisesi',
    'Ankara Bahçelievler Akşam Ticaret Lisesi',
    'Ankara Bahçelievler Deneme Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Bahçelievler Deneme Lisesi',
    'Ankara Bahçelievler Endüstri Meslek Lisesi',
    'Ankara Bahçelievler Teknik Lisesi',
    'Ankara Balgat Anadolu Meslek Lisesi',
    'Ankara Balgat Anadolu Teknik Lisesi',
    'Ankara Balgat Endüstri Meslek Lisesi',
    'Ankara Balgat Teknik Lisesi',
    'Ankara Başkent Lisesi',
    'Ankara Başkent Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Beşevler Lisesi',
    'Ankara Cebeci Anadolu Kız Meslek Lisesi',
    'Ankara Cebeci Atatürk Anadolu sağlık Meslek Lisesi',
    'Ankara Cebeci Atatürk Sağlık Meslek Lisesi',
    'Ankara Cebeci Kız Meslek Lisesi',
    'Ankara Cumhuriyet Akşam Ticaret Lisesi',
    'Ankara Cumhuriyet Lisesi',
    'Ankara Cumhuriyet Fen Lisesi',
    'Ankara Cumhuriyet Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Cumhuriyet Ticaret Meslek Lisesi',
    'Ankara Çağrıbey Anadolu Lisesi',
    'Ankara D.çağlar Ortopedik Engel.meslek Lisesi',
    'Ankara Dikmen Endüstri Meslek Lisesi',
    'Ankara Dikmen Lisesi',
    'Ankara Dikmen Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Dikmen N.ayaz Anadolu Kız Meslek L.',
    'Ankara Dikmen N.ayaz Kız Meslek Lisesi',
    'Ankara Dikmen N.ayaz Kız Teknik Lisesi',
    'Ankara Dikmen Teknik Lisesi',
    'Ankara Doğumevi Sağlık Meslek Lisesi',
    'Ankara Elektronik Astsubay Hazırlama Okulu',
    'Ankara Etlik Akşam Lisesi',
    'Ankara Etlik H.h.oğultürk Kız Meslek Lisesi',
    'Ankara Etlik Kız Meslek Lisesi',
    'Ankara Etlik Lisesi',
    'Ankara Etlik Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Ev Ekonomisi Meslek Lisesi',
    'Ankara Fen Lisesi',
    'Ankara Fethiye Kemal Mumcu Lisesi',
    'Ankara Gazi Akşam Lisesi',
    'Ankara Gazi Anadolu Lisesi',
    'Ankara Gazi Anadolu Meslek Lisesi',
    'Ankara Gazi Anadolu Teknik Lisesi',
    'Ankara Gazi Endüstri Meslek Lisesi',
    'Ankara Gazi Lisesi',
    'Ankara Gazi Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Gazi Teknik Lisesi',
    'Ankara Gaziçiftliği Akşam Lisesi',
    'Ankara Güven Lisesi',
    'Ankara Hacettepe Ünv.sağlık Koleji',
    'Ankara Hacı Ömer Tarman Anadolu Lisesi',
    'Ankara Hayvan Sağlığı Meslek Lisesi',
    'Ankara Iı.endüstri Meslek Lisesi',
    'Ankara İlköğretmen Okulu',
    'Ankara İmrahor Endüstri Meslek Lisesi',
    'Ankara İncesu Lisesi',
    'Ankara İnşaat Teknik Lisesi',
    'Ankara Jandarma Astsubay Hazırlama Okulu',
    'Ankara Kaya Bayazıtoğlu Lisesi',
    'Ankara Kaya Bayazıtoğlu Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Kız Lisesi',
    'Ankara Kız Meslek Lisesi',
    'Ankara Kimya Anadolu Teknik Lisesi',
    'Ankara Kimya Anadolu meslek Lisesi',
    'Ankara Kimya Meslek Lisesi',
    'Ankara Kimya Teknik Lisesi',
    'Ankara Kocatepe M.kemal Akşam Lisesi',
    'Ankara Kocatepe M.kemal Lisesi',
    'Ankara Kocatepe M.kemal Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Kurtuluş Akşam Lisesi',
    'Ankara Kurtuluş Lisesi',
    'Ankara Kurtuluş Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Laborant Meslek Lisesi',
    'Ankara Lisesi',
    'Ankara Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara M.rüştü Uzel Kimya Anadolu meslek L.',
    'Ankara M.rüştü Uzel Kimya Anadolu teknik Lisesi',
    'Ankara M.rüştü Uzel Kimya Meslek Lisesi',
    'Ankara M.rüştü Uzel Kimya Teknik Lisesi',
    'Ankara Maliye Meslek Lisesi',
    'Ankara Maliye Okulu',
    'Ankara Merkez İmam Hatip Lisesi',
    'Ankara Meteoroloji Meslek Lisesi',
    'Ankara Meteoroloji Teknik Lisesi',
    'Ankara Mızıka Astsubay Hazırlama Okulu',
    'Ankara Motor Meslek Lisesi',
    'Ankara Motor Teknik Lisesi',
    'Ankara Ortaköy 80.yıl Endüstri Meslek Lisesi',
    'Ankara Ortopedik Engelliler Meslek Lisesi',
    'Ankara Otelcilik Ve Turizm Meslek Lisesi',
    'Ankara Ömer Seyfettin Lisesi',
    'Ankara Ömer Seyfettin Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Özel Tevfik Fikret Lisesi',
    'Ankara Polis Koleji',
    'Ankara Pursaklar Fen Lisesi',
    'Ankara Radyo Tv Anadolu Meslek Lisesi',
    'Ankara Radyo Tv Anadolu Teknik Lisesi',
    'Ankara Reha Alemdaroğlu Lisesi',
    'Ankara Reha Alemdaroğlu Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Sağlık Astsubay Hazırlama Okulu',
    'Ankara Sekreterlik Meslek Lisesi',
    'Ankara Söğütözü Anadolu Lisesi',
    'Ankara Ssk Ankara Sağlık Meslek Lisesi',
    'Ankara Tapu Ve Kadastro Meslek Lisesi',
    'Ankara Ted Koleji Vakfı Özel Lisesi',
    'Ankara Tevfik İleri Anadolu İmam Hatip Lisesi',
    'Ankara Tevfik İleri İmam Hatip Lisesi  (Yabancı Dil Ağırlıklı)',
    'Ankara Tevfik İleri İmam Hatip Lisesi',
    'Ankara Ticaret Meslek Lisesi',
    'Ankara Türk Silahlı Kuv.sağlık Meslek Lisesi',
    'Ankara Türk Telekom Anadolu Meslek Lisesi',
    'Ankara Türk Telekom Anadolu Teknik Lisesi',
    'Ankara Uğurlu Lisesi',
    'Ankara Ulus Anadolu Meslek Lisesi',
    'Ankara Ulus Endüstri Meslek Lisesi',
    'Ankara Ulus Teknik Lisesi',
    'Ankara Ünv.tıp Fak.sağlık Bilim.koleji',
    'Ankara Y.beyazıt Anadolu Kız Meslek Lisesi',
    'Ankara Y.beyazıt Anadolu Meslek Lisesi',
    'Ankara Y.beyazıt Anadolu Teknik Lisesi',
    'Ankara Y.beyazıt Endüstri Meslek Lisesi',
    'Ankara Y.beyazıt Teknik Lisesi',
    'Ankara Yapı Meslek Lisesi',
    'Ankara Yenişehir Sağlık Meslek Lisesi',
    'Ankara Yıldırım Beyazıt Akşam Lisesi',
    'Ankara Yıldırım Beyazıt Anadolu Lisesi',
    'Ankara Yıldırım Beyazıt Kız Meslek Lisesi',
    'Ankara Yıldırım Beyazıt Lisesi',
    'Ankara Yıldırım Beyazıt Lisesi (Yabancı Dil Ağırlıklı)',
    'Ankara Z.hanım Anadolu Kız Meslek Lisesi',
    'Ankara Zübeyde Hanım Kız Meslek Lisesi',
    'Ankara Zübeyde Hanım Kız Teknik Lisesi',
    'Aöd Tefev Ankara Özel Tevfik Fikret Lisesi',
    'Ayaş Çok Programlı Lisesi',
    'Ayaş İmam Hatip Lisesi',
    'Ayaş Lisesi',
    'Bala Afşar Çok Programlı Lisesi',
    'Bala Atatürk Endüstri Meslek Lisesi',
    'Bala Endüstri Meslek Lisesi',
    'Bala İmam Hatip Lisesi',
    'Bala Kemal Şahin Sağlık Meslek Lisesi',
    'Bala Kesikköprü Çok Programlı Lisesi',
    'Bala Laboratuvar Sağlık Meslek Lisesi',
    'Bala Lisesi',
    'Bala Lisesi (Yabancı Dil Ağırlıklı)',
    'Bala Sağlık Meslek Lisesi',
    'Başkent Üniversitesi Özel Ayşeabla Fen Lisesi',
    'Başkent Üniversitesi Özel Ayşeabla Lisesi',
    'Başkent Üniversitesi Özel Başkent Fen Lisesi',
    'Batıkent Ş.evliyagil Anadolu  İletişim Meslek Lisesi ',
    'Beypazarı Anadolu Lisesi',
    'Beypazarı Endüstri Meslek Lisesi',
    'Beypazarı İmam Hatip Lisesi',
    'Beypazarı Kız Meslek Lisesi',
    'Beypazarı Lisesi',
    'Beypazarı Lisesi (Yabancı Dil Ağırlıklı)',
    'Beypazarı N.karaoğuz Vakfı Anadolu Lisesi',
    'Beypazarı Sağlık Meslek Lisesi',
    'Beypazarı Ticaret Meslek Lisesi',
    'Beypazarı Tolunay Özaka Sağlık Meslek Lisesi',
    'Bilkent Ün.müzik-s.sanat.fak.müzik Haz.o',
    'Bilkent Üniversitesi Hazırlık Okulu',
    'Çamlıdere Çok Programlı Lisesi',
    'Çamlıdere İmam Hatip Lisesi',
    'Çamlıdere Lisesi',
    'Çankaya 100.yıl Anadolu Kız Meslek Lisesi',
    'Çankaya 100.yıl Kız Meslek Lisesi',
    'Çankaya 100.yıl Uyg.sanat.and.kız Meslek Lisesi',
    'Çankaya 50.yıl Lisesi',
    'Çankaya 50.yıl Lisesi (Yabancı Dil Ağırlıklı)',
    'Çankaya Akdere Ticaret Meslek Lisesi',
    'Çankaya Aliye Yahşi Anadolu Kız Meslek Lisesi',
    'Çankaya Anadolu Lisesi',
    'Çankaya Anadolu Otel ve Turizm Meslek Lisesi',
    'Çankaya Atatürk Lisesi',
    'Çankaya Balgat Aliye Yahşi Kız Meslek Lisesi',
    'Çankaya Balgat Anadolu Teknik Lisesi',
    'Çankaya Cumhuriyet Anadolu Tic.meslek Lisesi',
    'Çankaya Gaziosmanpaşa Anadolu Kız Meslek Lisesi',
    'Çankaya Gaziosmanpaşa Kız Meslek Lisesi',
    'Çankaya İmam Hatip Lisesi',
    'Çankaya Kemal Yurtbilir Anadolu Lisesi',
    'Çankaya Kılıçarslan Lisesi',
    'Çankaya Kılıçarslan Lisesi (Yabancı Dil Ağırlıklı)',
    'Çankaya Küçükesat Lisesi',
    'Çankaya Lisesi',
    'Çankaya Lisesi (Yabancı Dil Ağırlıklı)',
    'Çankaya M.emin Resulzade Anadolu Lisesi',
    'Çankaya M.emin Resulzade Lisesi',
    'Çankaya Milli Piyango Anadolu Lisesi',
    'Çankaya S.mehmet Paşa Lisesi',
    'Çankaya S.mehmet Paşa Lisesi (Yabancı Dil Ağırlıklı)',
    'Çankaya Seyranbağları Lisesi',
    'Çankaya Seyranbağları Lisesi (Yabancı Dil Ağırlıklı)',
    'Çankaya Tarım Meslek Lisesi',
    'Çankaya Tınaztepe Lisesi',
    'Çankaya Tınaztepe Lisesi (Yabancı Dil Ağırlıklı)',
    'Çubuk Anadolu Lisesi',
    'Çubuk Anadolu Meslek Lisesi',
    'Çubuk Endüstri Meslek Lisesi',
    'Çubuk Hayri Aslan Kız Meslek Lisesi',
    'Çubuk Hayri Aslan Kız Teknik Lisesi',
    'Çubuk İmam Hatip Lisesi',
    'Çubuk Kız Meslek Lisesi',
    'Çubuk Lisesi',
    'Çubuk Lisesi (Yabancı Dil Ağırlıklı)',
    'Çubuk Sağlık Meslek Lisesi',
    'Çubuk Teknik Lisesi',
    'Çubuk Ticaret Meslek Lisesi',
    'Dr.binnaz Ege-dr.rıdvan Ege Anadolu Lisesi',
    'Elmadağ Endüstri Meslek Lisesi',
    'Elmadağ Hasanoğlan Fatih Lisesi',
    'Elmadağ Hasanoğlan Kız Meslek Lisesi',
    'Elmadağ Hasanoğlan Spor Meslek Lisesi',
    'Elmadağ İmam Hatip Lisesi',
    'Elmadağ Kız Meslek Lisesi',
    'Elmadağ Lisesi',
    'Elmadağ Lisesi (Yabancı Dil Ağırlıklı)',
    'Elmadağ Mesleki Ve Teknik Eğitim Merkezi',
    'Elmadağ Sağlık Meslek Lisesi',
    'Etimesgut Anadolu Kız Meslek Lisesi',
    'Etimesgut Anadolu Lisesi',
    'Etimesgut Dr.r.saydam Sağlık Meslek Lisesi',
    'Etimesgut Eryaman Lisesi',
    'Etimesgut Eryaman Lisesi (Yabancı Dil Ağırlıklı)',
    'Etimesgut Güvercinlik Endüstri Meslek Lisesi',
    'Etimesgut Kız Meslek Lisesi',
    'Etimesgut Lisesi',
    'Etimesgut Mehmetçik Lisesi',
    'Etimesgut Mehmetçik Lisesi (Yabancı Dil Ağırlıklı)',
    'Etimesgut Mustafa Kemal Sağlık Meslek Lisesi',
    'Etimesgut Sağlık Meslek Lisesi',
    'Etimesgut Ticaret Meslek Lisesi',
    'Evren Lisesi',
    'Gölbaşı A.güneşoğlu Anadolu Lisesi',
    'Gölbaşı Ali Güder Çok Programlı Lisesi',
    'Gölbaşı Anadolu Lisesi',
    'Gölbaşı Dr.ş.tombuloğlu Lisesi',
    'Gölbaşı Dr.ş.tombuloğlu Lisesi (Yabancı Dil Ağırlıklı)',
    'Gölbaşı Endüstri Meslek Lisesi',
    'Gölbaşı İmam Hatip Lisesi',
    'Gölbaşı Kız Meslek Lisesi',
    'Gölbaşı Sağlık Meslek Lisesi',
    'Güdül Çağa Lisesi',
    'Güdül Çok Programlı Lisesi',
    'Güdül Lisesi',
    'Haymana Bumsuz Çok Programlı Lisesi',
    'Haymana Çok Programlı Lisesi',
    'Haymana Endüstri Meslek Lisesi',
    'Haymana İmam Hatip Lisesi',
    'Haymana Kız Meslek Lisesi',
    'Haymana Lisesi',
    'Haymana Oyaca Çok Programlı Lisesi',
    'Haymana Oyaca Lisesi',
    'İncesu Anadolu Lisesi',
    'Kalecik Çok Programlı Lisesi',
    'Kalecik Endüstri Meslek Lisesi',
    'Kalecik İmam Hatip Lisesi',
    'Kalecik Lisesi',
    'Kalecik Lisesi (Yabancı Dil Ağırlıklı)',
    'Kalecik M.yıldırım Ticaret Meslek Lisesi',
    'Kalecik Mesleki Ve Teknik Eğitim Merkezi',
    'Kalecik Sağlık Meslek Lisesi',
    'Kalecik Şehit M.yıldırım Ticaret Meslek Lisesi',
    'Kalecik Ticaret Meslek Lisesi',
    'Kazan Çok Programlı Lisesi',
    'Kazan Çok Programlı Lisesi (Yabancı Dil Ağırlıklı)',
    'Kazan Efes Anadolu Meslek Lisesi',
    'Kazan Efes Endüstri Meslek Lisesi',
    'Kazan İmam Hatip Lisesi',
    'Kazan Lisesi',
    'Kazan Mustafa Hakan Güvençer Anadolu Lisesi',
    'Keçiören 70.yıl Çevre Sağlığı Meslek Lisesi',
    'Keçiören A.m.özünecek Cum.75.yıl Lisesi',
    'Keçiören Adalet Meslek Lisesi',
    'Keçiören Akşam Lisesi',
    'Keçiören Anadolu Meslek Lisesi',
    'Keçiören Anadolu Teknik Lisesi',
    'Keçiören Bağlum Lisesi',
    'Keçiören Bekir Gökdağ Lisesi',
    'Keçiören Çevre Sağlığı Meslek Lisesi',
    'Keçiören Endüstri Meslek Lisesi',
    'Keçiören Etlik Anadolu Kız Meslek Lisesi',
    'Keçiören Etlik H.h.oğultürk Anadolu Kız Meslek Lisesi',
    'Keçiören F.kemal Mumcu Anadolu Lisesi',
    'Keçiören F.sultan Mehmet Lisesi',
    'Keçiören F.sultan Mehmet Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören Farabi Lisesi',
    'Keçiören Farabi Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören Genç Osman Lisesi',
    'Keçiören Genç Osman Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören İmam Hatip Lisesi',
    'Keçiören İncirli Endüstri Meslek Lisesi',
    'Keçiören İncirli Lisesi',
    'Keçiören İncirli Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören İncirli Teknik Lisesi',
    'Keçiören Kalaba Anadolu Kız Meslek Lisesi',
    'Keçiören Kalaba Anadolu Lisesi',
    'Keçiören Kalaba Kız Meslek Lisesi',
    'Keçiören Kalaba Lisesi',
    'Keçiören Kalaba Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören Kanuni Lisesi',
    'Keçiören Kanuni Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören Laboratuvar Sağlık Meslek Lisesi',
    'Keçiören Lisesi',
    'Keçiören Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören Pursaklar Anadolu Lisesi',
    'Keçiören Pursaklar İmkb Anadolu Meslek Lisesi',
    'Keçiören Pursaklar İmkb Endüstri Meslek Lisesi',
    'Keçiören Pursaklar Lisesi',
    'Keçiören Pursaklar Sağlık Meslek Lisesi',
    'Keçiören Pursaklar Y.k.-m.s.sağlık Meslek Lisesi',
    'Keçiören Rauf Denktaş Lisesi',
    'Keçiören Rauf Denktaş Lisesi (Yabancı Dil Ağırlıklı)',
    'Keçiören Sağlık Meslek Lisesi',
    'Keçiören Teknik Lisesi',
    'Keçiören Yamantürk Ticaret Meslek Lisesi',
    'Kızılcahamam Anadolu Lisesi',
    'Kızılcahamam Anadolu Meslek Lisesi',
    'Kızılcahamam Anadolu Teknik Lisesi',
    'Kızılcahamam Anadolu otel.ve Turizm Meslek Lisesi',
    'Kızılcahamam Endüstri Meslek Lisesi',
    'Kızılcahamam İmam Hatip Lisesi',
    'Kızılcahamam Kız Meslek Lisesi',
    'Kızılcahamam Lisesi',
    'Kızılcahamam Lisesi (Yabancı Dil Ağırlıklı)',
    'Kızılcahamam Sağlık Meslek Lisesi',
    'Kızılcahamam Teknik Lisesi',
    'Kızılcahamam Ticaret Meslek Lisesi',
    'MEV Özel Ankara Fen Lisesi',
    'MEV Özel Ankara Lisesi',
    'MEV Özel Köksal Toptan Lisesi',
    'Mamak Ali Naili Erdem Anadolu Lisesi',
    'Mamak Ali Naili Erdem Lisesi',
    'Mamak Anadolu Kız Meslek Lisesi',
    'Mamak Anadolu Lisesi',
    'Mamak Battalgazi Anadolu Meslek Lisesi',
    'Mamak Battalgazi Endüstri Meslek Lisesi',
    'Mamak Battalgazi Teknik Lisesi',
    'Mamak Cumhuriyet Anadolu Lisesi',
    'Mamak Ege Lisesi',
    'Mamak Gülveren Lisesi',
    'Mamak Hurin Yavuzalp Lisesi',
    'Mamak İmam Hatip Lisesi',
    'Mamak Kız Meslek Lisesi',
    'Mamak Kutludüğün Çok Programlı Lisesi',
    'Mamak Lisesi',
    'Mamak Lisesi (Yabancı Dil Ağırlıklı)',
    'Mamak Nahit Menteşe Lisesi',
    'Mamak Nahit Menteşe Lisesi (Yabancı Dil Ağırlıklı)',
    'Mamak Niğbolu Lisesi',
    'Mamak Niğbolu Lisesi (Yabancı Dil Ağırlıklı)',
    'Mamak Tuzluçayır Lisesi',
    'Mamak Türközü İmrahor Teknik Lisesi',
    'Mamak Türközü Oğuzhan Anadolu Meslek Lisesi',
    'Mamak Türközü Oğuzhan Endüstri Meslek Lisesi',
    'Mamak Türközü Oğuzhan Teknik Lisesi',
    'Mamak Türközü Şehit N.pamir Lisesi (Yabancı Dil Ağırlıklı)',
    'Mamak Türközü Şehit N.pamir Lisesi',
    'Mamak Üreğil Anadolu Kız Meslek Lisesi',
    'Mamak Üreğil Kız Meslek Lisesi',
    'Mamak Yunus Emre Ticaret Meslek Lisesi',
    'Nallıhan Çayırhan Çok Programlı Lisesi',
    'Nallıhan Çayırhan Lisesi',
    'Nallıhan Çok Programlı Lisesi',
    'Nallıhan Endüstri Meslek Lisesi',
    'Nallıhan F.güngör Endüstri Meslek Lisesi',
    'Nallıhan F.güngör Teknik Lisesi',
    'Nallıhan İmam Hatip Lisesi',
    'Nallıhan Kız Meslek Lisesi',
    'Nallıhan Lisesi',
    'Nallıhan Lisesi (Yabancı Dil Ağırlıklı)',
    'Nallıhan Sağlık Meslek Lisesi',
    'Nallıhan Sarıyar Lisesi',
    'Nallıhan Ş.ö.b Ticaret Meslek Lisesi',
    'Nallıhan Şehit Ömer Boztepe Ç.p.l',
    'Nallıhan Şehit Ömer Boztepe Ç.p.l (Yabancı Dil Ağırlıklı)',
    'Nallıhan Şehit V.arıcı Anadolu Lisesi',
    'Nallıhan Ticaret Meslek Lisesi',
    'Nallıhan Turgay Ciner Çok Programlı Lisesi',
    'Nermin-mehmet Çekiç Anadolu Lisesi',
    'Odtü Geliştirme Vakfı Özel Lisesi',
    'Özel Ahmet Ulusoy Fen Lisesi',
    'Özel Ahmet Ulusoy Lisesi',
    'Özel Akyazılı Lisesi',
    'Özel Alp Lisesi',
    'Özel Alp Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Altın Fen Lisesi',
    'Özel Ankara Aziziye Lisesi',
    'Özel Ankara Aziziye Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Ankara Öncü Lisesi',
    'Özel Ankara Üni.geliştirme Vakfı Özel Lisesi',
    'Özel Arı Fen Lisesi',
    'Özel Arı Lisesi',
    'Özel Atılım Fen Lisesi',
    'Özel Atılım Lisesi',
    'Özel Atılım Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Aydeniz Lisesi',
    'Özel Aydın Anadolu Lisesi',
    'Özel Aykan Lisesi',
    'Özel Ayşeabla Lisesi',
    'Özel Baştem Anadolu otel.ve Turizm Meslek Lisesi',
    'Özel Bilgi Ankara Lisesi',
    'Özel Bilgi Etlik Lisesi',
    'Özel Bilim Akşam Lisesi',
    'Özel Bilim Fen Lisesi',
    'Özel Bilim Lisesi',
    'Özel Bilkent Uluslararası Lisesi',
    'Özel Büyük Lise',
    'Özel Ceceli Lisesi',
    'Özel Çağrı Fen Lisesi',
    'Özel Çağrı Kız Fen Lisesi',
    'Özel Çağrı Kız Lisesi',
    'Özel Çağrı Kız Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Çağrı Lisesi',
    'Özel Çağrı Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Evrensel Fen Lisesi',
    'Özel Evrensel Lisesi',
    'Özel Fatoşabla Lisesi',
    'Özel Ferda Lisesi',
    'Özel Ferda Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Gönen Akşam Lisesi',
    'Özel Gürsoylar Lisesi',
    'Özel Hafsa Sultan Fen Lisesi',
    'Özel Hafsa Sultan Kız Fen Lisesi',
    'Özel Hafsa Sultan Kız Lisesi',
    'Özel Hafsa Sultan Kız Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Hafsa Sultan Lisesi',
    'Özel Hafsa Sultan Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel İlkadım Lisesi',
    'Özel İlkem Lisesi',
    'Özel İpek Kız Lisesi',
    'Özel İpek Lisesi',
    'Özel Meltem Lisesi',
    'Özel Muradiye Erkek Fen Lisesi',
    'Özel Muradiye Erkek Lisesi',
    'Özel Muradiye Kız Fen Lisesi',
    'Özel Muradiye Kız Lisesi',
    'Özel Muradiye Kız Meslek Lisesi',
    'Özel Nene Hatun Fen Lisesi',
    'Özel Nene Hatun Lisesi',
    'Özel Nene Hatun Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Nene Hatun Meslek Lisesi',
    'Özel Olgun Lisesi',
    'Özel Özer Lisesi',
    'Özel Polatlı Samanyolu Lisesi',
    'Özel Polatlı Taceddin Lisesi',
    'Özel Samanyolu Erkek Fen Lisesi',
    'Özel Samanyolu Erkek Lisesi',
    'Özel Samanyolu Erkek Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Samanyolu Fen Lisesi',
    'Özel Samanyolu Keçiören Fen Lisesi',
    'Özel Samanyolu Keçiören Lisesi',
    'Özel Samanyolu Lisesi',
    'Özel Selen Lisesi',
    'Özel Sevgi Kız Lisesi',
    'Özel Sevgi Lisesi',
    'Özel Sincan Lisesi',
    'Özel Şafak Lisesi',
    'Özel Türk Yurdu Lisesi',
    'Özel Türk Yurdu Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Türkav Lisesi',
    'Özel Yavuz Sultan Fen Lisesi',
    'Özel Yavuz Sultan Lisesi',
    'Özel Yavuz Sultan Lisesi (Yabancı Dil Ağırlıklı)',
    'Özel Yenişehir Lisesi',
    'Özel Yüce Fen Lisesi',
    'Özel Yüce Lisesi',
    'Özel Yükseliş I Lisesi',
    'Özel Yükseliş Iı Lisesi',
    'Özel Yükseliş Lisesi',
    'Pkev Özel Ayhan Gökay Busch Lisesi',
    'Polatlı Akşam Lisesi',
    'Polatlı Anadolu İmam Hatip Lisesi',
    'Polatlı Anadolu Kız Meslek Lisesi',
    'Polatlı Anadolu Lisesi',
    'Polatlı Anadolu Teknik Lisesi',
    'Polatlı Anadolu Ticaret Meslek Lisesi',
    'Polatlı Atatürk Lisesi',
    'Polatlı Çok Programlı Lisesi',
    'Polatlı Endüstri Meslek Lisesi',
    'Polatlı İmam Hatip Lisesi',
    'Polatlı Kız Meslek Lisesi',
    'Polatlı Lisesi',
    'Polatlı Lisesi (Yabancı Dil Ağırlıklı)',
    'Polatlı Sağlık Meslek Lisesi',
    'Polatlı Ted Koleji Vakfı Özel Lisesi',
    'Polatlı Teknik Lisesi',
    'Polatlı Temelli Çok Programlı Lisesi',
    'Polatlı Ticaret Meslek Lisesi',
    'Sincan A.andiçen Ticaret Meslek Lisesi',
    'Sincan Akşam Lisesi',
    'Sincan Anadolu Kız Meslek Lisesi',
    'Sincan Anadolu Lisesi',
    'Sincan Endüstri Meslek Lisesi',
    'Sincan Fatih Endüstri Meslek Lisesi',
    'Sincan Fatih Özcan Sabancı Anadolu Kız Meslek Lisesi',
    'Sincan Fatih Özcan Sabancı Kız Meslek Lisesi',
    'Sincan Fatih Teknik Lisesi',
    'Sincan İbni Sina Lisesi',
    'Sincan İbni Sina Lisesi (Yabancı Dil Ağırlıklı)',
    'Sincan İmam Hatip Lisesi',
    'Sincan İmkb Ticaret Meslek Lisesi',
    'Sincan Kız Meslek Lisesi',
    'Sincan Lisesi',
    'Sincan Lisesi (Yabancı Dil Ağırlıklı)',
    'Sincan Sağlık Meslek Lisesi',
    'Sincan Süleyman Demirel Anadolu Lisesi',
    'Sincan Teknik Lisesi',
    'Sincan Yenikent Endüstri Meslek Lisesi',
    'Sincan Yenikent Lisesi',
    'Sincan Yunus Emre Lisesi',
    'Sincan Yunus Emre Lisesi (Yabancı Dil Ağırlıklı)',
    'Süleyman Demirel Sağlık Meslek Lisesi',
    'Şereflikoçhisar Anadolu Lisesi',
    'Şereflikoçhisar Anadolu Teknik Lisesi',
    'Şereflikoçhisar Çalören Lisesi',
    'Şereflikoçhisar Dr.s.uzun Sağlık Meslek Lisesi',
    'Şereflikoçhisar Endüstri Meslek Lisesi',
    'Şereflikoçhisar İmam Hatip Lisesi',
    'Şereflikoçhisar Kaçarlı Lisesi',
    'Şereflikoçhisar Kız Meslek Lisesi',
    'Şereflikoçhisar Lisesi',
    'Şereflikoçhisar Lisesi (Yabancı Dil Ağırlıklı)',
    'Şereflikoçhisar Sağlık Meslek Lisesi',
    'Şereflikoçhisar Teknik Lisesi',
    'Şereflikoçhisar Ticaret Meslek Lisesi',
    'Yahyalar Lisesi',
    'Yanimahalle Batıkent Anadolu Meslek Lisesi',
    'Yenimahalle 75.yıl Lisesi',
    'Yenimahalle 75.yıl Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Alparslan Lisesi',
    'Yenimahalle Alparslan Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Anadolu Kız Meslek L.',
    'Yenimahalle Anadolu Meslek Lisesi',
    'Yenimahalle Anadolu Teknik Lisesi',
    'Yenimahalle Anadolu mahalli İdareler Meslek Lisesi',
    'Yenimahalle Batıkent Endüstri Meslek Lisesi',
    'Yenimahalle Batıkent Lisesi',
    'Yenimahalle Batıkent Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Batıkent Ş.evliyagil A.il.ml',
    'Yenimahalle Batıkent Ş.evliyagil Anadolu Temel Lisesi',
    'Yenimahalle Batıkent Ş.evliyagil Ticaret Meslek Lisesi',
    'Yenimahalle Batıkent Teknik Lisesi',
    'Yenimahalle Çiğdemtepe Anadolu Meslek Lisesi',
    'Yenimahalle Çiğdemtepe Anadolu Teknik Lisesi',
    'Yenimahalle Çiğdemtepe Endüstri Meslek Lisesi',
    'Yenimahalle Çiğdemtepe Teknik Lisesi',
    'Yenimahalle Demetevler İmam Hatip Lisesi',
    'Yenimahalle Demetevler Lisesi',
    'Yenimahalle Endüstri Meslek Lisesi',
    'Yenimahalle Gaziçiftliği Lisesi',
    'Yenimahalle Gaziçiftliği Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Halide Edip Lisesi',
    'Yenimahalle Halide Edip Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle İnşaat Anadolu Teknik Lisesi',
    'Yenimahalle Kız Meslek Lisesi',
    'Yenimahalle Mahalli İdareler Meslek Lisesi',
    'Yenimahalle Mehmet Akif Ersoy Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Mehmet Akif Ersoy Lisesi',
    'Yenimahalle Mimar Sinan Lisesi',
    'Yenimahalle Mimar Sinan Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Mobil Lisesi',
    'Yenimahalle Mobil Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Mustafa Kemal Akşam Lisesi',
    'Yenimahalle Mustafa Kemal Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Mustafa Kemal Lisesi',
    'Yenimahalle Prof.dr.ş.r.hatipoğlu Lisesi',
    'Yenimahalle Prof.dr.ş.r.hatipoğlu Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Şentepe Lisesi',
    'Yenimahalle Şentepe Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Tarım Meslek Lisesi',
    'Yenimahalle Teknik Lisesi',
    'Yenimahalle Ticaret Meslek Lisesi',
    'Yenimahalle Yahya Kemal Beyatlı Lisesi',
    'Yenimahalle Yahya Kemal Beyatlı Lisesi (Yabancı Dil Ağırlıklı)',
    'Yenimahalle Yunus Emre Anadolu Kız Meslek Lisesi',
    'Yenimahalle Yunus Emre Kız Meslek Lisesi'
  ]
};
